import Link from 'next/link';
import { compileEp001PerShotCharacterIntegration } from '@/lib/tivvlejoy-ep001-per-shot-character-integration';

export const dynamic = 'force-dynamic';
export const metadata = { title: 'Episode 1 Per-Shot Character Integration | TivvleJoy', description: 'Deterministic shot-level character, dialogue and performance integration plan.' };

export default function Ep001PerShotCharacterIntegrationPage() {
  const plan = compileEp001PerShotCharacterIntegration();
  return <main className="mx-auto min-h-screen w-full max-w-7xl space-y-4 px-4 py-6 sm:px-6 sm:py-10">
    <section className="studio-card p-4 sm:p-6">
      <Link href="/episode-one/character-scene-integration" className="inline-flex min-h-touch items-center text-sm font-bold text-[var(--color-primary)]">← Character scene integration</Link>
      <p className="mt-3 text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-primary)]">Episode 1 shot integration</p>
      <h1 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">Character controls, dialogue and performance markers are bound shot-by-shot</h1>
      <p className="mt-3 max-w-4xl text-sm leading-6 text-[var(--color-text-muted)]">This plan derives only from canonical EP001 timing, dialogue and character-specific SFX evidence. It never assumes that a character is absent from picture merely because they have no dialogue or sound marker in a shot.</p>
      <dl className="mt-5 grid gap-px overflow-hidden rounded-xl bg-[var(--color-border)] sm:grid-cols-5">{[['Shots',plan.metrics.shotCount],['Dialogue',plan.metrics.dialogueLineCount],['Markers',plan.metrics.performanceMarkerCount],['Executed',plan.metrics.executedShotCount],['Approved',plan.metrics.approvedShotCount]].map(([k,v]) => <div key={String(k)} className="bg-[var(--color-surface)] p-3"><dt className="text-xs font-bold uppercase text-[var(--color-text-muted)]">{k}</dt><dd className="mt-1 font-display text-2xl font-bold">{v}</dd></div>)}</dl>
      <p className="mt-4 break-all font-mono text-[11px]">Plan SHA-256: {plan.perShotCharacterIntegrationSha256}</p>
    </section>
    <section className="space-y-3">{plan.shots.map((shot) => <article key={shot.shotId} className="studio-card p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-display text-xl font-bold">{shot.shotId}</p><p className="mt-1 font-mono text-[11px] text-[var(--color-text-muted)]">frames {shot.inFrame}–{shot.outFrame} · {shot.durationFrames} frames</p></div><span className="status-warning rounded-full px-3 py-1 text-xs font-bold">not executed</span></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{shot.characterPlans.map((character) => <div key={character.characterId} className="rounded-xl border border-[var(--color-border)] p-3"><p className="font-bold">{character.characterId === 'CHAR_PIP_001' ? 'Pip' : 'Goat'}</p><p className="mt-1 font-mono text-[11px]">{character.actionName}</p><p className="mt-3 text-xs font-bold uppercase text-[var(--color-text-muted)]">Controls</p><p className="mt-1 font-mono text-[11px] leading-5">{character.requiredCanonicalControls.join(', ')}</p>{character.dialogueLineIds.length ? <p className="mt-3 text-xs">Dialogue: {character.dialogueLineIds.join(', ')}</p> : null}{character.performanceMarkers.length ? <ul className="mt-3 list-disc space-y-1 pl-5 text-xs text-[var(--color-text-muted)]">{character.performanceMarkers.map((marker) => <li key={marker.sfxEventId}>frame {marker.frame}: {marker.syncTarget}</li>)}</ul> : null}</div>)}</div>{shot.unknownScenePresence.length ? <p className="mt-4 rounded-xl bg-[var(--color-surface-subtle)] p-3 text-xs leading-5 text-[var(--color-text-muted)]">Picture presence not yet proven from audio evidence: {shot.unknownScenePresence.map((id) => id === 'CHAR_PIP_001' ? 'Pip' : 'Goat').join(', ')}. Final blocking must resolve visibility without inferring absence.</p> : null}</article>)}</section>
    <section className="rounded-3xl border border-[var(--color-warning)] bg-[var(--color-warning-soft)] p-4 text-sm leading-6 text-[var(--color-warning-foreground)]"><p className="font-bold">Shot integration is prepared, not animated.</p><p className="mt-1">Approved character packages, exact adapter receipts, real voice timing, admitted scenery, Blender execution and human shot approval all remain required.</p></section>
  </main>;
}
