import Link from 'next/link';
import { compileEp001ShotAnimationEvidence } from '@/lib/tivvlejoy-ep001-shot-animation-evidence';

export const dynamic = 'force-dynamic';
export const metadata = { title: 'Episode 1 Shot Animation Evidence | TivvleJoy', description: 'Per-shot playblast, still, machine-check and human-review evidence contract.' };

export default function Ep001ShotAnimationEvidencePage() {
  const plan = compileEp001ShotAnimationEvidence();
  return <main className="mx-auto min-h-screen w-full max-w-7xl space-y-4 px-4 py-6 sm:px-6 sm:py-10">
    <section className="studio-card p-4 sm:p-6"><Link href="/episode-one/dialogue-animation-manifest" className="inline-flex min-h-touch items-center text-sm font-bold text-[var(--color-primary)]">← Dialogue animation manifest</Link><p className="mt-3 text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-primary)]">Episode 1 animation evidence</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">Every shot already has a playblast and review-proof contract</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-[var(--color-text-muted)]">Before any animation can be approved, each shot must produce its exact review playblast, representative stills, machine metrics and immutable evidence manifest, followed by human visual review.</p><dl className="mt-5 grid gap-px overflow-hidden rounded-xl bg-[var(--color-border)] sm:grid-cols-5">{[['Shots',plan.metrics.shotCount],['Playblasts',plan.metrics.playblastCountRequired],['Stills',plan.metrics.requiredStillCount],['Evidence received',plan.metrics.receivedEvidenceManifestCount],['Approved',plan.metrics.humanApprovedShotCount]].map(([k,v]) => <div key={String(k)} className="bg-[var(--color-surface)] p-3"><dt className="text-xs font-bold uppercase text-[var(--color-text-muted)]">{k}</dt><dd className="mt-1 font-display text-2xl font-bold">{v}</dd></div>)}</dl></section>
    <section className="space-y-3">{plan.shots.map((shot) => <article key={shot.shotId} className="studio-card p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-display text-xl font-bold">{shot.shotId}</p><p className="mt-1 font-mono text-[11px]">frames {shot.inFrame}–{shot.outFrame}</p></div><span className="status-warning rounded-full px-3 py-1 text-xs font-bold">evidence not received</span></div><div className="mt-4 grid gap-4 lg:grid-cols-3"><div><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Outputs</p><p className="mt-1 break-all font-mono text-[11px]">{shot.outputs.playblast.key}</p><p className="mt-1 text-xs">{shot.outputs.stills.length} stills · {shot.outputs.playblast.width}×{shot.outputs.playblast.height}</p></div><div><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Machine checks</p><ul className="mt-1 list-disc space-y-1 pl-5 text-xs text-[var(--color-text-muted)]">{shot.machineChecks.slice(0,4).map((item) => <li key={item}>{item}</li>)}</ul></div><div><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Human checks</p><ul className="mt-1 list-disc space-y-1 pl-5 text-xs text-[var(--color-text-muted)]">{shot.humanChecks.slice(0,4).map((item) => <li key={item}>{item}</li>)}</ul></div></div>{shot.mapTransitionIds.length ? <p className="mt-3 rounded-xl bg-[var(--color-surface-subtle)] p-3 text-xs">Prop transition continuity: {shot.mapTransitionIds.join(', ')}</p> : null}</article>)}</section>
    <section className="rounded-3xl border border-[var(--color-warning)] bg-[var(--color-warning-soft)] p-4 text-sm leading-6 text-[var(--color-warning-foreground)]"><p className="font-bold">No shot evidence has been produced yet.</p><p className="mt-1">This contract defines acceptance evidence only; it launches no Blender job and grants no shot approval.</p><p className="mt-3 break-all font-mono text-[11px]">Evidence contract SHA-256: {plan.shotAnimationEvidenceSha256}</p></section>
  </main>;
}
