import { approvalReceiptHash, inspectionEvidenceHash } from './inspection';
import { assetDependencySha256, buildApprovedAssetRegistry } from './registry';
import {
  APPROVAL_RECEIPT_SCHEMA,
  APPROVED_ENVIRONMENT_ASSET_SCHEMA,
  INSPECTION_EVIDENCE_SCHEMA,
  type ApprovalReceipt,
  type ApprovedEnvironmentAsset,
  type CanonicalState,
  type CoverageCategory,
  type InspectionEvidence,
  type ProductionSemanticRole,
  type QualityTier,
} from './types';

const SHA = {
  srcA: 'aa'.repeat(32),
  srcB: 'ab'.repeat(32),
  srcC: 'ac'.repeat(32),
  srcD: 'ad'.repeat(32),
  srcE: 'ae'.repeat(32),
  srcF: 'af'.repeat(32),
  srcG: 'a1'.repeat(32),
  srcH: 'a2'.repeat(32),
  srcI: 'a3'.repeat(32),
  srcJ: 'a4'.repeat(32),
  srcK: 'a5'.repeat(32),
  srcL: 'a6'.repeat(32),
  srcM: 'a7'.repeat(32),
  srcN: 'a8'.repeat(32),
  srcO: 'a9'.repeat(32),
  srcP: 'ba'.repeat(32),
  srcQ: 'bb'.repeat(32),
  srcR: 'bc'.repeat(32),
  srcS: 'bd'.repeat(32),
  srcT: 'be'.repeat(32),
  srcU: 'bf'.repeat(32),
  srcV: 'c1'.repeat(32),
  srcW: 'c2'.repeat(32),
  srcX: 'c3'.repeat(32),
  invalid: 'not-a-hash',
} as const;

function evidence(input: {
  sourceId: string;
  sourceSha256: string;
  assetId: string;
  kind: string;
  roles: ProductionSemanticRole[];
  categories: CoverageCategory[];
  archetypes: string[];
  biomes: string[];
  groupId: string;
  state: CanonicalState;
  visual?: string[];
  extras?: Partial<InspectionEvidence>;
}): InspectionEvidence {
  const draft: Omit<InspectionEvidence, 'inspectionSha256'> = {
    schemaVersion: INSPECTION_EVIDENCE_SCHEMA,
    sourceId: input.sourceId,
    sourceReceiptRef: `receipt:${input.sourceId}`,
    sourceSha256: input.sourceSha256,
    storedByteSize: 1024,
    expectedByteSize: 1024,
    sizeVerified: true,
    inspectionId: `insp:${input.assetId}`,
    inspectionVersion: '1',
    inspectionPerformedAt: '2026-08-19T00:00:00.000Z',
    containerIntegrity: 'PASSED',
    discoveredAssetId: input.assetId,
    discoveredAssetKind: input.kind,
    nativeFormat: 'SYNTHETIC',
    blenderCompatibility: 'COMPATIBLE',
    geometryMetrics: { verts: 100 },
    materialMetrics: { count: 1 },
    textureMetrics: { count: 1 },
    dimensions: { x: 1, y: 1, z: 1 },
    originAssessment: 'centered',
    scaleAssessment: 'meters',
    externalDependencies: [],
    requiredAddonDependencies: [],
    missingTextureRefs: [],
    missingExternalRefs: [],
    safetyAssessment: { scripts: 'SAFE', network: 'SAFE', shell: 'SAFE' },
    provenanceState: 'RESOLVED',
    licenseState: 'APPROVED_INTERNAL',
    visualEvidenceRefs: input.visual ?? (input.roles.some((role) => role.includes('HERO')) ? [`viz:${input.assetId}`] : []),
    styleFingerprint: 'TIVVLEJOY_STORYBOOK',
    semanticClassification: {
      roles: input.roles,
      coverageCategories: input.categories,
      archetypes: input.archetypes,
      biomes: input.biomes,
      kind: input.kind,
    },
    canonicalRecommendation: { groupId: input.groupId, state: input.state },
    inspectionWarnings: [],
    inspectionBlockers: [],
    ...input.extras,
  };
  return { ...draft, inspectionSha256: inspectionEvidenceHash(draft) };
}

function approval(input: {
  assetId: string;
  version: string;
  sourceId: string;
  sourceSha256: string;
  inspection: InspectionEvidence;
  roles: ProductionSemanticRole[];
  categories: CoverageCategory[];
  archetypes: string[];
  decision?: ApprovalReceipt['approvalDecision'];
  visualRequired?: boolean;
  visualSatisfied?: boolean;
}): ApprovalReceipt {
  const draft: Omit<ApprovalReceipt, 'approvalSha256'> = {
    schemaVersion: APPROVAL_RECEIPT_SCHEMA,
    approvalReceiptId: `apr:${input.assetId}`,
    assetId: input.assetId,
    assetVersion: input.version,
    sourceId: input.sourceId,
    sourceReceiptRef: `receipt:${input.sourceId}`,
    sourceSha256: input.sourceSha256,
    inspectionReceiptRef: input.inspection.inspectionId,
    inspectionSha256: input.inspection.inspectionSha256,
    approvalDecision: input.decision ?? 'APPROVED',
    approvedSemanticRoles: input.roles,
    approvedCoverageCategories: input.categories,
    approvedArchetypes: input.archetypes,
    visualApprovalRequired: input.visualRequired ?? input.roles.some((role) => role.includes('HERO')),
    visualApprovalSatisfied: input.visualSatisfied ?? input.roles.some((role) => role.includes('HERO')),
    licenseState: 'APPROVED_INTERNAL',
    provenanceState: 'RESOLVED',
    approvedAt: '2026-08-19T00:00:00.000Z',
    approvedByPolicy: 'TIVVLEJOY_EXPLICIT_APPROVAL',
    sourceImmutable: true,
    rawRedistributionAllowed: false,
  };
  return { ...draft, approvalSha256: approvalReceiptHash(draft) };
}

export function makeApprovedAsset(input: {
  assetId: string;
  version?: string;
  sourceId: string;
  sourceSha256: string;
  displayName: string;
  originalFilename?: string;
  kind: string;
  roles: ProductionSemanticRole[];
  categories: CoverageCategory[];
  archetypes: string[];
  biomes: string[];
  depths: ApprovedEnvironmentAsset['depthEligibility'];
  qualities: QualityTier[];
  groupId: string;
  canonicalState: CanonicalState;
  fallbackEligible?: boolean;
  complexity?: number;
  approvalState?: ApprovedEnvironmentAsset['approvalState'];
  style?: ApprovedEnvironmentAsset['styleCompatibility'];
  blender?: ApprovedEnvironmentAsset['blenderCompatibility'];
  license?: ApprovedEnvironmentAsset['licenseState'];
  provenance?: ApprovedEnvironmentAsset['provenanceState'];
  worldBuilderEligible?: boolean;
  shotAssemblyEligible?: boolean;
  provider?: ApprovedEnvironmentAsset['provider'];
  lifecycle?: ApprovedEnvironmentAsset['lifecycleState'];
  seasons?: ApprovedEnvironmentAsset['seasonCompatibility'];
  weather?: ApprovedEnvironmentAsset['weatherCompatibility'];
  supersedesAssetId?: string | null;
  duplicateOfAssetId?: string | null;
  sourceReceiptRef?: string;
  inspectionReceiptRef?: string;
  approvalReceiptRef?: string;
  sourceShaOverride?: string;
  inspectionShaOverride?: string;
  approvalShaOverride?: string;
}): ApprovedEnvironmentAsset {
  const version = input.version ?? '1';
  const insp = evidence({
    sourceId: input.sourceId,
    sourceSha256: input.sourceSha256,
    assetId: input.assetId,
    kind: input.kind,
    roles: input.roles,
    categories: input.categories,
    archetypes: input.archetypes,
    biomes: input.biomes,
    groupId: input.groupId,
    state: input.canonicalState,
  });
  const apr = approval({
    assetId: input.assetId,
    version,
    sourceId: input.sourceId,
    sourceSha256: input.sourceSha256,
    inspection: insp,
    roles: input.roles,
    categories: input.categories,
    archetypes: input.archetypes,
    decision: input.approvalState ?? 'APPROVED',
  });
  const draft: ApprovedEnvironmentAsset = {
    schemaVersion: APPROVED_ENVIRONMENT_ASSET_SCHEMA,
    assetId: input.assetId,
    assetVersion: version,
    sourceId: input.sourceId,
    sourceReceiptRef: input.sourceReceiptRef ?? `receipt:${input.sourceId}`,
    sourceSha256: input.sourceShaOverride ?? input.sourceSha256,
    inspectionReceiptRef: input.inspectionReceiptRef ?? insp.inspectionId,
    inspectionSha256: input.inspectionShaOverride ?? insp.inspectionSha256,
    approvalReceiptRef: input.approvalReceiptRef ?? apr.approvalReceiptId,
    approvalSha256: input.approvalShaOverride ?? apr.approvalSha256,
    displayName: input.displayName,
    originalFilename: input.originalFilename,
    assetKind: input.kind,
    semanticRoles: input.roles,
    coverageCategories: input.categories,
    archetypeCompatibility: input.archetypes,
    biomeTags: input.biomes,
    depthEligibility: input.depths,
    qualityEligibility: input.qualities,
    seasonCompatibility: input.seasons ?? ['ANY'],
    weatherCompatibility: input.weather ?? ['ANY'],
    styleCompatibility: input.style ?? 'EXACT',
    blenderCompatibility: input.blender ?? 'COMPATIBLE',
    complexityClass: input.complexity ?? 2,
    canonicalGroupId: input.groupId,
    canonicalState: input.canonicalState,
    duplicateOfAssetId: input.duplicateOfAssetId ?? null,
    supersedesAssetId: input.supersedesAssetId ?? null,
    fallbackEligible: input.fallbackEligible ?? input.canonicalState === 'ALTERNATE_APPROVED',
    approvalState: input.approvalState ?? 'APPROVED',
    provenanceState: input.provenance ?? 'RESOLVED',
    licenseState: input.license ?? 'APPROVED_INTERNAL',
    sourceImmutable: true,
    rawRedistributionAllowed: false,
    worldBuilderEligible: input.worldBuilderEligible ?? true,
    shotAssemblyEligible: input.shotAssemblyEligible ?? true,
    assetDependencySha256: '',
    lifecycleState: input.lifecycle ?? 'APPROVED',
    provider: input.provider ?? 'APPROVED_LIBRARY',
    botaniqActivated: false,
    geoScatterIntegrated: false,
  };
  return { ...draft, assetDependencySha256: assetDependencySha256(draft) };
}

function villageBuilding(kind: 'HERO' | 'SUPPORT', id: string, sha: string, filename: string, extras: Partial<Parameters<typeof makeApprovedAsset>[0]> = {}) {
  return makeApprovedAsset({
    assetId: id,
    sourceId: `SRC_SYN_VILLAGE_${kind}`,
    sourceSha256: sha,
    displayName: kind === 'HERO' ? 'Village hero building' : 'Village supporting building',
    originalFilename: filename,
    kind: 'BUILDING',
    roles: [kind === 'HERO' ? 'BUILDING_HERO' : 'BUILDING_SUPPORT'],
    categories: ['architecture', 'hero_locations'],
    archetypes: kind === 'HERO' ? ['BAKERY_EXTERIOR', 'VILLAGE_SQUARE', 'MARKET_STREET'] : ['BAKERY_EXTERIOR', 'VILLAGE_SQUARE', 'GENERIC'],
    biomes: ['village'],
    depths: ['MIDGROUND'],
    qualities: kind === 'HERO' ? ['HERO', 'SUPPORTING', 'BACKGROUND'] : ['SUPPORTING', 'BACKGROUND'],
    groupId: 'CANON_VILLAGE_BUILDING',
    canonicalState: kind === 'HERO' ? 'PRIMARY' : 'ALTERNATE_APPROVED',
    fallbackEligible: kind === 'SUPPORT',
    complexity: kind === 'HERO' ? 3 : 2,
    ...extras,
  });
}

export const SYNTHETIC_APPROVED_ASSETS = {
  villageHero: villageBuilding('HERO', 'AA_VILLAGE_HERO_BUILDING', SHA.srcA, 'village-hero.blend'),
  villageSupport: villageBuilding('SUPPORT', 'AA_VILLAGE_SUPPORT_BUILDING', SHA.srcB, 'village-support.blend'),
  tavernShell: makeApprovedAsset({
    assetId: 'AA_TAVERN_INTERIOR_SHELL',
    sourceId: 'SRC_SYN_TAVERN',
    sourceSha256: SHA.srcC,
    displayName: 'Tavern interior shell',
    originalFilename: 'tavern-shell.blend',
    kind: 'INTERIOR',
    roles: ['INTERIOR_SHELL'],
    categories: ['interiors', 'architecture'],
    archetypes: ['BAKERY_INTERIOR', 'COZY_HOME_INTERIOR', 'GENERIC_INTERIOR_ROOM'],
    biomes: ['village'],
    depths: ['MIDGROUND'],
    qualities: ['HERO', 'SUPPORTING'],
    groupId: 'CANON_TAVERN_INTERIOR',
    canonicalState: 'PRIMARY',
  }),
  tavernProp: makeApprovedAsset({
    assetId: 'AA_TAVERN_FURNITURE_PROP',
    sourceId: 'SRC_SYN_TAVERN',
    sourceSha256: SHA.srcC,
    displayName: 'Tavern furniture prop',
    originalFilename: 'tavern-furniture.blend',
    kind: 'PROP',
    roles: ['INTERIOR_PROP'],
    categories: ['props', 'interiors'],
    archetypes: ['BAKERY_INTERIOR'],
    biomes: ['village'],
    depths: ['MIDGROUND', 'FOREGROUND'],
    qualities: ['SUPPORTING', 'BACKGROUND'],
    groupId: 'CANON_TAVERN_PROP',
    canonicalState: 'PRIMARY',
  }),
  forestHeroTree: makeApprovedAsset({
    assetId: 'AA_FOREST_HERO_TREE',
    sourceId: 'SRC_SYN_FOREST',
    sourceSha256: SHA.srcD,
    displayName: 'Forest hero tree',
    originalFilename: 'forest-hero-tree.blend',
    kind: 'TREE',
    roles: ['TREE_HERO'],
    categories: ['vegetation', 'hero_locations'],
    archetypes: ['FOREST_PATH', 'FOREST_CLEARING', 'DEEP_FOREST'],
    biomes: ['forest'],
    depths: ['MIDGROUND'],
    qualities: ['HERO', 'SUPPORTING', 'BACKGROUND'],
    groupId: 'CANON_FOREST_TREE',
    canonicalState: 'PRIMARY',
  }),
  forestSupportTree: makeApprovedAsset({
    assetId: 'AA_FOREST_SUPPORT_TREE',
    sourceId: 'SRC_SYN_FOREST',
    sourceSha256: SHA.srcD,
    displayName: 'Forest supporting tree',
    originalFilename: 'forest-support-tree.blend',
    kind: 'TREE',
    roles: ['TREE_SUPPORT'],
    categories: ['vegetation'],
    archetypes: ['FOREST_PATH', 'GENERIC'],
    biomes: ['forest'],
    depths: ['MIDGROUND'],
    qualities: ['SUPPORTING', 'BACKGROUND'],
    groupId: 'CANON_FOREST_TREE_SUPPORT',
    canonicalState: 'PRIMARY',
  }),
  forestBackgroundTree: makeApprovedAsset({
    assetId: 'AA_FOREST_BACKGROUND_TREE',
    sourceId: 'SRC_SYN_FOREST',
    sourceSha256: SHA.srcD,
    displayName: 'Forest background tree',
    originalFilename: 'forest-bg-tree.blend',
    kind: 'TREE',
    roles: ['TREE_BACKGROUND'],
    categories: ['vegetation', 'backgrounds'],
    archetypes: ['FOREST_PATH', 'GENERIC'],
    biomes: ['forest'],
    depths: ['BACKGROUND'],
    qualities: ['BACKGROUND'],
    groupId: 'CANON_FOREST_TREE_BG',
    canonicalState: 'PRIMARY',
    complexity: 1,
  }),
  grass: makeApprovedAsset({
    assetId: 'AA_GRASS',
    sourceId: 'SRC_SYN_VEG',
    sourceSha256: SHA.srcE,
    displayName: 'Grass',
    kind: 'VEGETATION',
    roles: ['GRASS'],
    categories: ['vegetation'],
    archetypes: ['GENERIC', 'FOREST_PATH', 'MEADOW'],
    biomes: ['forest', 'meadow', 'village'],
    depths: ['FOREGROUND', 'MIDGROUND'],
    qualities: ['SUPPORTING', 'BACKGROUND'],
    groupId: 'CANON_GRASS',
    canonicalState: 'PRIMARY',
    complexity: 1,
  }),
  flowers: makeApprovedAsset({
    assetId: 'AA_FLOWERS',
    sourceId: 'SRC_SYN_VEG',
    sourceSha256: SHA.srcE,
    displayName: 'Flowers',
    kind: 'VEGETATION',
    roles: ['FLOWERS'],
    categories: ['vegetation'],
    archetypes: ['SPRING_MEADOW', 'GENERIC'],
    biomes: ['meadow', 'village'],
    depths: ['FOREGROUND'],
    qualities: ['SUPPORTING', 'BACKGROUND'],
    groupId: 'CANON_FLOWERS',
    canonicalState: 'PRIMARY',
  }),
  shrubs: makeApprovedAsset({
    assetId: 'AA_SHRUBS',
    sourceId: 'SRC_SYN_VEG',
    sourceSha256: SHA.srcE,
    displayName: 'Shrubs',
    kind: 'VEGETATION',
    roles: ['SHRUBS'],
    categories: ['vegetation'],
    archetypes: ['GENERIC', 'FOREST_PATH'],
    biomes: ['forest', 'village'],
    depths: ['FOREGROUND', 'MIDGROUND'],
    qualities: ['SUPPORTING', 'BACKGROUND'],
    groupId: 'CANON_SHRUBS',
    canonicalState: 'PRIMARY',
  }),
  mountainHero: makeApprovedAsset({
    assetId: 'AA_MOUNTAIN_HERO',
    sourceId: 'SRC_SYN_MOUNTAIN',
    sourceSha256: SHA.srcF,
    displayName: 'Mountain hero',
    originalFilename: 'mountain-hero.blend',
    kind: 'MOUNTAIN',
    roles: ['MOUNTAIN_HERO', 'ROCK'],
    categories: ['terrain', 'hero_locations'],
    archetypes: ['MOUNTAIN_OVERLOOK', 'ROCKY_TRAIL'],
    biomes: ['mountain'],
    depths: ['MIDGROUND'],
    qualities: ['HERO', 'SUPPORTING', 'BACKGROUND'],
    groupId: 'CANON_MOUNTAIN',
    canonicalState: 'PRIMARY',
  }),
  mountainBackground: makeApprovedAsset({
    assetId: 'AA_MOUNTAIN_BACKGROUND',
    sourceId: 'SRC_SYN_MOUNTAIN',
    sourceSha256: SHA.srcF,
    displayName: 'Mountain background range',
    originalFilename: 'mountain-bg.blend',
    kind: 'MOUNTAIN',
    roles: ['MOUNTAIN_BACKGROUND'],
    categories: ['terrain', 'backgrounds'],
    archetypes: ['MOUNTAIN_OVERLOOK', 'GENERIC'],
    biomes: ['mountain', 'village'],
    depths: ['BACKGROUND'],
    qualities: ['BACKGROUND'],
    groupId: 'CANON_MOUNTAIN_BG',
    canonicalState: 'PRIMARY',
    complexity: 1,
  }),
  rock: makeApprovedAsset({
    assetId: 'AA_ROCK',
    sourceId: 'SRC_SYN_MOUNTAIN',
    sourceSha256: SHA.srcF,
    displayName: 'Rock',
    kind: 'ROCK',
    roles: ['ROCK'],
    categories: ['terrain'],
    archetypes: ['ROCKY_TRAIL', 'RIVERBANK', 'GENERIC'],
    biomes: ['mountain', 'river'],
    depths: ['FOREGROUND', 'MIDGROUND'],
    qualities: ['SUPPORTING', 'BACKGROUND'],
    groupId: 'CANON_ROCK',
    canonicalState: 'PRIMARY',
  }),
  water: makeApprovedAsset({
    assetId: 'AA_RIVER_WATER',
    sourceId: 'SRC_SYN_WATER',
    sourceSha256: SHA.srcG,
    displayName: 'River water',
    kind: 'WATER',
    roles: ['WATER'],
    categories: ['water'],
    archetypes: ['RIVERBANK', 'RIVER_CROSSING'],
    biomes: ['river'],
    depths: ['MIDGROUND', 'BACKGROUND'],
    qualities: ['SUPPORTING', 'BACKGROUND'],
    groupId: 'CANON_WATER',
    canonicalState: 'PRIMARY',
  }),
  sky: makeApprovedAsset({
    assetId: 'AA_SKY',
    sourceId: 'SRC_SYN_SKY',
    sourceSha256: SHA.srcH,
    displayName: 'Sky',
    kind: 'SKY',
    roles: ['SKY'],
    categories: ['backgrounds', 'lighting'],
    archetypes: ['GENERIC'],
    biomes: ['village', 'forest', 'mountain', 'river'],
    depths: ['BACKGROUND'],
    qualities: ['BACKGROUND'],
    groupId: 'CANON_SKY',
    canonicalState: 'PRIMARY',
    complexity: 1,
  }),
  signage: makeApprovedAsset({
    assetId: 'AA_SIGNAGE',
    sourceId: 'SRC_SYN_SIGN',
    sourceSha256: SHA.srcI,
    displayName: 'Signage',
    kind: 'SIGN',
    roles: ['SIGNAGE'],
    categories: ['story_signage', 'props'],
    archetypes: ['BAKERY_EXTERIOR', 'MARKET_STREET', 'SNOW_VILLAGE'],
    biomes: ['village'],
    depths: ['FOREGROUND', 'MIDGROUND'],
    qualities: ['SUPPORTING', 'BACKGROUND'],
    groupId: 'CANON_SIGNAGE',
    canonicalState: 'PRIMARY',
  }),
  backgroundFill: makeApprovedAsset({
    assetId: 'AA_BACKGROUND_FILL',
    sourceId: 'SRC_SYN_BG',
    sourceSha256: SHA.srcJ,
    displayName: 'Background fill',
    kind: 'BACKGROUND',
    roles: ['BACKGROUND_FILL'],
    categories: ['backgrounds'],
    archetypes: ['GENERIC', 'SNOW_VILLAGE'],
    biomes: ['village', 'snow'],
    depths: ['BACKGROUND'],
    qualities: ['BACKGROUND'],
    groupId: 'CANON_BG_FILL',
    canonicalState: 'PRIMARY',
    complexity: 1,
  }),
  villageAlternate: makeApprovedAsset({
    assetId: 'AA_VILLAGE_ALT_BUILDING',
    sourceId: 'SRC_SYN_VILLAGE_ALT',
    sourceSha256: SHA.srcK,
    displayName: 'Village alternate building',
    originalFilename: 'village-alt.blend',
    kind: 'BUILDING',
    roles: ['BUILDING_HERO'],
    categories: ['architecture', 'hero_locations'],
    archetypes: ['BAKERY_EXTERIOR'],
    biomes: ['village'],
    depths: ['MIDGROUND'],
    qualities: ['HERO', 'SUPPORTING', 'BACKGROUND'],
    groupId: 'CANON_VILLAGE_BUILDING',
    canonicalState: 'ALTERNATE_APPROVED',
    fallbackEligible: true,
    complexity: 4,
  }),
  duplicateTree: makeApprovedAsset({
    assetId: 'AA_FOREST_TREE_DUPLICATE',
    sourceId: 'SRC_SYN_FOREST_DUP',
    sourceSha256: SHA.srcD,
    displayName: 'Forest tree duplicate',
    originalFilename: 'forest-tree-copy.blend',
    kind: 'TREE',
    roles: ['TREE_HERO'],
    categories: ['vegetation'],
    archetypes: ['FOREST_PATH'],
    biomes: ['forest'],
    depths: ['MIDGROUND'],
    qualities: ['HERO'],
    groupId: 'CANON_FOREST_TREE',
    canonicalState: 'DUPLICATE',
    duplicateOfAssetId: 'AA_FOREST_HERO_TREE',
  }),
  archivalWrapper: makeApprovedAsset({
    assetId: 'AA_TAVERN_WRAPPER_ARCHIVAL',
    sourceId: 'SRC_SYN_TAVERN_WRAPPER',
    sourceSha256: SHA.srcL,
    displayName: 'Tavern ZIP wrapper archival',
    originalFilename: 'tavern.zip',
    kind: 'WRAPPER',
    roles: ['INTERIOR_SHELL'],
    categories: ['interiors'],
    archetypes: ['BAKERY_INTERIOR'],
    biomes: ['village'],
    depths: ['MIDGROUND'],
    qualities: ['HERO'],
    groupId: 'CANON_TAVERN_INTERIOR',
    canonicalState: 'ARCHIVAL',
    approvalState: 'ARCHIVAL_ONLY',
    worldBuilderEligible: false,
    shotAssemblyEligible: false,
    lifecycle: 'ARCHIVAL_ONLY',
  }),
  blockedAsset: makeApprovedAsset({
    assetId: 'AA_BLOCKED_SOURCE',
    sourceId: 'SRC_SYN_BLOCKED',
    sourceSha256: SHA.srcM,
    displayName: 'Blocked asset',
    kind: 'BUILDING',
    roles: ['BUILDING_HERO'],
    categories: ['architecture'],
    archetypes: ['BAKERY_EXTERIOR'],
    biomes: ['village'],
    depths: ['MIDGROUND'],
    qualities: ['HERO'],
    groupId: 'CANON_BLOCKED',
    canonicalState: 'PRIMARY',
    approvalState: 'BLOCKED',
    worldBuilderEligible: false,
    shotAssemblyEligible: false,
    lifecycle: 'BLOCKED_LICENSE',
  }),
  quarantinedAsset: makeApprovedAsset({
    assetId: 'AA_QUARANTINED',
    sourceId: 'SRC_SYN_QUAR',
    sourceSha256: SHA.srcN,
    displayName: 'Quarantined asset',
    kind: 'BUILDING',
    roles: ['BUILDING_HERO'],
    categories: ['architecture'],
    archetypes: ['BAKERY_EXTERIOR'],
    biomes: ['village'],
    depths: ['MIDGROUND'],
    qualities: ['HERO'],
    groupId: 'CANON_QUAR',
    canonicalState: 'PRIMARY',
    approvalState: 'QUARANTINED',
    lifecycle: 'QUARANTINED',
    worldBuilderEligible: false,
    shotAssemblyEligible: false,
  }),
  licenseBlocked: makeApprovedAsset({
    assetId: 'AA_LICENSE_BLOCKED',
    sourceId: 'SRC_SYN_LICENSE',
    sourceSha256: SHA.srcO,
    displayName: 'License-blocked asset',
    kind: 'BUILDING',
    roles: ['BUILDING_SUPPORT'],
    categories: ['architecture'],
    archetypes: ['BAKERY_EXTERIOR'],
    biomes: ['village'],
    depths: ['MIDGROUND'],
    qualities: ['SUPPORTING'],
    groupId: 'CANON_LICENSE',
    canonicalState: 'PRIMARY',
    license: 'BLOCKED',
    approvalState: 'APPROVED',
  }),
  styleIncompatible: makeApprovedAsset({
    assetId: 'AA_STYLE_INCOMPATIBLE',
    sourceId: 'SRC_SYN_STYLE',
    sourceSha256: SHA.srcP,
    displayName: 'Style-incompatible asset',
    kind: 'BUILDING',
    roles: ['BUILDING_HERO'],
    categories: ['architecture'],
    archetypes: ['BAKERY_EXTERIOR'],
    biomes: ['village'],
    depths: ['MIDGROUND'],
    qualities: ['HERO'],
    groupId: 'CANON_STYLE',
    canonicalState: 'PRIMARY',
    style: 'INCOMPATIBLE',
  }),
  blenderIncompatible: makeApprovedAsset({
    assetId: 'AA_BLENDER_INCOMPATIBLE',
    sourceId: 'SRC_SYN_BLEND_BAD',
    sourceSha256: SHA.srcQ,
    displayName: 'Blender-incompatible asset',
    kind: 'BUILDING',
    roles: ['BUILDING_HERO'],
    categories: ['architecture'],
    archetypes: ['BAKERY_EXTERIOR'],
    biomes: ['village'],
    depths: ['MIDGROUND'],
    qualities: ['HERO'],
    groupId: 'CANON_BLEND',
    canonicalState: 'PRIMARY',
    blender: 'INCOMPATIBLE',
  }),
  hashInvalid: makeApprovedAsset({
    assetId: 'AA_HASH_INVALID',
    sourceId: 'SRC_SYN_BADHASH',
    sourceSha256: SHA.srcR,
    displayName: 'Hash-invalid fixture',
    kind: 'BUILDING',
    roles: ['BUILDING_HERO'],
    categories: ['architecture'],
    archetypes: ['BAKERY_EXTERIOR'],
    biomes: ['village'],
    depths: ['MIDGROUND'],
    qualities: ['HERO'],
    groupId: 'CANON_BADHASH',
    canonicalState: 'PRIMARY',
    sourceShaOverride: SHA.invalid,
  }),
  missingReceipt: makeApprovedAsset({
    assetId: 'AA_MISSING_RECEIPT',
    sourceId: 'SRC_SYN_NORECEIPT',
    sourceSha256: SHA.srcS,
    displayName: 'Missing-receipt fixture',
    kind: 'BUILDING',
    roles: ['BUILDING_HERO'],
    categories: ['architecture'],
    archetypes: ['BAKERY_EXTERIOR'],
    biomes: ['village'],
    depths: ['MIDGROUND'],
    qualities: ['HERO'],
    groupId: 'CANON_NORECEIPT',
    canonicalState: 'PRIMARY',
    sourceReceiptRef: '',
  }),
  missingInspection: makeApprovedAsset({
    assetId: 'AA_MISSING_INSPECTION',
    sourceId: 'SRC_SYN_NOINSP',
    sourceSha256: SHA.srcT,
    displayName: 'Missing-inspection fixture',
    kind: 'BUILDING',
    roles: ['BUILDING_HERO'],
    categories: ['architecture'],
    archetypes: ['BAKERY_EXTERIOR'],
    biomes: ['village'],
    depths: ['MIDGROUND'],
    qualities: ['HERO'],
    groupId: 'CANON_NOINSP',
    canonicalState: 'PRIMARY',
    inspectionReceiptRef: '',
  }),
  missingApproval: makeApprovedAsset({
    assetId: 'AA_MISSING_APPROVAL',
    sourceId: 'SRC_SYN_NOAPR',
    sourceSha256: SHA.srcU,
    displayName: 'Missing-approval fixture',
    kind: 'BUILDING',
    roles: ['BUILDING_HERO'],
    categories: ['architecture'],
    archetypes: ['BAKERY_EXTERIOR'],
    biomes: ['village'],
    depths: ['MIDGROUND'],
    qualities: ['HERO'],
    groupId: 'CANON_NOAPR',
    canonicalState: 'PRIMARY',
    approvalReceiptRef: '',
  }),
  unknownProvenance: makeApprovedAsset({
    assetId: 'AA_UNKNOWN_PROVENANCE',
    sourceId: 'SRC_SYN_PROV',
    sourceSha256: SHA.srcV,
    displayName: 'Unknown provenance fixture',
    kind: 'BUILDING',
    roles: ['BUILDING_SUPPORT'],
    categories: ['architecture'],
    archetypes: ['BAKERY_EXTERIOR'],
    biomes: ['village'],
    depths: ['MIDGROUND'],
    qualities: ['SUPPORTING'],
    groupId: 'CANON_PROV',
    canonicalState: 'PRIMARY',
    provenance: 'UNKNOWN',
  }),
  botaniqUploadOnly: makeApprovedAsset({
    assetId: 'AA_BOTANIQ_UPLOAD_ONLY',
    sourceId: 'SRC_BOTANIQ_FULL_7_2_0',
    sourceSha256: SHA.srcW,
    displayName: 'Botaniq upload-only synthetic',
    originalFilename: 'botaniq_full-7.2.0.paq.zip',
    kind: 'VEGETATION',
    roles: ['TREE_HERO'],
    categories: ['vegetation'],
    archetypes: ['FOREST_PATH'],
    biomes: ['forest'],
    depths: ['MIDGROUND'],
    qualities: ['HERO'],
    groupId: 'CANON_BOTANIQ',
    canonicalState: 'PRIMARY',
    provider: 'BOTANIQ_IF_APPROVED',
    worldBuilderEligible: false,
    shotAssemblyEligible: false,
    approvalState: 'ARCHIVAL_ONLY',
    lifecycle: 'ARCHIVAL_ONLY',
  }),
  futureMeadowKit: makeApprovedAsset({
    assetId: 'AA_FUTURE_MEADOW_KIT',
    sourceId: 'SRC_SYN_FUTURE_MEADOW',
    sourceSha256: SHA.srcX,
    displayName: 'Newly approved future meadow kit',
    originalFilename: 'future-meadow.blend',
    kind: 'VEGETATION',
    roles: ['FLOWERS'],
    categories: ['vegetation'],
    archetypes: ['SPRING_MEADOW'],
    biomes: ['meadow'],
    depths: ['FOREGROUND'],
    qualities: ['SUPPORTING', 'BACKGROUND'],
    groupId: 'CANON_FUTURE_MEADOW',
    canonicalState: 'PRIMARY',
  }),
  genericBuilding: makeApprovedAsset({
    assetId: 'AA_GENERIC_BUILDING',
    sourceId: 'SRC_SYN_GENERIC_BUILDING',
    sourceSha256: SHA.srcB,
    displayName: 'Generic building',
    kind: 'BUILDING',
    roles: ['BUILDING_HERO'],
    categories: ['architecture'],
    archetypes: ['GENERIC'],
    biomes: ['generic'],
    depths: ['MIDGROUND'],
    qualities: ['HERO', 'SUPPORTING', 'BACKGROUND'],
    groupId: 'CANON_GENERIC_BUILDING',
    canonicalState: 'PRIMARY',
    complexity: 5,
    style: 'HARMONIZABLE',
  }),
};

export const SELECTABLE_SYNTHETIC_ASSETS = [
  SYNTHETIC_APPROVED_ASSETS.villageHero,
  SYNTHETIC_APPROVED_ASSETS.villageSupport,
  SYNTHETIC_APPROVED_ASSETS.tavernShell,
  SYNTHETIC_APPROVED_ASSETS.tavernProp,
  SYNTHETIC_APPROVED_ASSETS.forestHeroTree,
  SYNTHETIC_APPROVED_ASSETS.forestSupportTree,
  SYNTHETIC_APPROVED_ASSETS.forestBackgroundTree,
  SYNTHETIC_APPROVED_ASSETS.grass,
  SYNTHETIC_APPROVED_ASSETS.flowers,
  SYNTHETIC_APPROVED_ASSETS.shrubs,
  SYNTHETIC_APPROVED_ASSETS.mountainHero,
  SYNTHETIC_APPROVED_ASSETS.mountainBackground,
  SYNTHETIC_APPROVED_ASSETS.rock,
  SYNTHETIC_APPROVED_ASSETS.water,
  SYNTHETIC_APPROVED_ASSETS.sky,
  SYNTHETIC_APPROVED_ASSETS.signage,
  SYNTHETIC_APPROVED_ASSETS.backgroundFill,
  SYNTHETIC_APPROVED_ASSETS.villageAlternate,
  SYNTHETIC_APPROVED_ASSETS.genericBuilding,
];

export const DIAGNOSTIC_SYNTHETIC_ASSETS = [
  ...SELECTABLE_SYNTHETIC_ASSETS,
  SYNTHETIC_APPROVED_ASSETS.duplicateTree,
  SYNTHETIC_APPROVED_ASSETS.archivalWrapper,
  SYNTHETIC_APPROVED_ASSETS.blockedAsset,
  SYNTHETIC_APPROVED_ASSETS.quarantinedAsset,
  SYNTHETIC_APPROVED_ASSETS.licenseBlocked,
  SYNTHETIC_APPROVED_ASSETS.styleIncompatible,
  SYNTHETIC_APPROVED_ASSETS.blenderIncompatible,
  SYNTHETIC_APPROVED_ASSETS.hashInvalid,
  SYNTHETIC_APPROVED_ASSETS.missingReceipt,
  SYNTHETIC_APPROVED_ASSETS.missingInspection,
  SYNTHETIC_APPROVED_ASSETS.missingApproval,
  SYNTHETIC_APPROVED_ASSETS.unknownProvenance,
  SYNTHETIC_APPROVED_ASSETS.botaniqUploadOnly,
];

export function syntheticRegistry(assets: ApprovedEnvironmentAsset[] = DIAGNOSTIC_SYNTHETIC_ASSETS) {
  return buildApprovedAssetRegistry({ assets, generatedFromAuditSha256: null });
}

export function conflictRegistry() {
  const twin = makeApprovedAsset({
    assetId: 'AA_VILLAGE_HERO_CONFLICT',
    sourceId: 'SRC_SYN_VILLAGE_CONFLICT',
    sourceSha256: SHA.srcA,
    displayName: 'Conflicting village hero',
    kind: 'BUILDING',
    roles: ['BUILDING_HERO'],
    categories: ['architecture'],
    archetypes: ['BAKERY_EXTERIOR'],
    biomes: ['village'],
    depths: ['MIDGROUND'],
    qualities: ['HERO'],
    groupId: 'CANON_VILLAGE_BUILDING',
    canonicalState: 'PRIMARY',
  });
  return buildApprovedAssetRegistry({
    assets: [SYNTHETIC_APPROVED_ASSETS.villageHero, twin],
  });
}

export function largeSyntheticRegistry(count = 320) {
  const extras = Array.from({ length: count }, (_, index) =>
    makeApprovedAsset({
      assetId: `AA_FILL_${String(index).padStart(4, '0')}`,
      sourceId: `SRC_SYN_FILL_${index}`,
      sourceSha256: (index % 256).toString(16).padStart(2, '0').repeat(32),
      displayName: `Fill ${index}`,
      kind: 'BACKGROUND',
      roles: ['BACKGROUND_FILL'],
      categories: ['backgrounds'],
      archetypes: ['GENERIC'],
      biomes: ['generic'],
      depths: ['BACKGROUND'],
      qualities: ['BACKGROUND'],
      groupId: `CANON_FILL_${index}`,
      canonicalState: 'PRIMARY',
      complexity: 8,
    }),
  );
  return buildApprovedAssetRegistry({
    assets: [...SELECTABLE_SYNTHETIC_ASSETS, ...extras],
  });
}

export const SYNTHETIC_SHA = SHA;
