export const ASSEMBLY_MANIFEST_SCHEMA = 'TIVVLEJOY_SHOT_ASSEMBLY_MANIFEST_V1' as const;
export const CHARACTER_SLOT_SCHEMA = 'TIVVLEJOY_CHARACTER_ASSEMBLY_SLOT_V1' as const;
export const ENVIRONMENT_SLOT_SCHEMA = 'TIVVLEJOY_ENVIRONMENT_ASSET_SLOT_V1' as const;
export const LOCATION_INSTANCE_SCHEMA = 'TIVVLEJOY_LOCATION_INSTANCE_V1' as const;
export const CAMERA_BINDING_SCHEMA = 'TIVVLEJOY_CAMERA_BINDING_V1' as const;
export const LIGHTING_BINDING_SCHEMA = 'TIVVLEJOY_LIGHTING_BINDING_V1' as const;
export const STORY_PROP_CONTINUITY_SCHEMA = 'TIVVLEJOY_STORY_PROP_CONTINUITY_V1' as const;
export const DEPENDENCY_GRAPH_SCHEMA = 'TIVVLEJOY_SHOT_DEPENDENCY_GRAPH_V1' as const;
export const CHANGE_IMPACT_SCHEMA = 'TIVVLEJOY_CHANGE_IMPACT_REPORT_V1' as const;
export const BLENDER_ASSEMBLY_REQUEST_SCHEMA = 'TIVVLEJOY_BLENDER_ASSEMBLY_REQUEST_V1' as const;

export const UNRESOLVED_PRODUCTION_RIG = 'UNRESOLVED_PRODUCTION_RIG' as const;
export const UNRESOLVED = 'UNRESOLVED' as const;

export const RESOLUTION_STATES = [
  'RESOLVED_APPROVED',
  'RESOLVED_RESTRICTED',
  'UNRESOLVED_SOURCE',
  'UNRESOLVED_VERSION',
  'UNRESOLVED_HASH',
  'UNRESOLVED_PROVENANCE',
  'BLOCKED_QUARANTINED',
  'BLOCKED_UNAPPROVED',
  'BLOCKED_HASH_MISMATCH',
  'BLOCKED_VERSION_MISMATCH',
] as const;
export type ResolutionState = (typeof RESOLUTION_STATES)[number];

export const ASSEMBLY_STAGES = [
  '01_VALIDATE_SHOT_PACKAGE',
  '02_RESOLVE_LOCATION',
  '03_RESOLVE_ASSET_RECEIPTS',
  '04_BUILD_COLLECTION_TREE',
  '05_INSTANCE_ENVIRONMENT',
  '06_APPLY_LOCATION_DELTA',
  '07_PLACE_STORY_PROPS',
  '08_PLACE_CHARACTERS',
  '09_BIND_CAMERA',
  '10_APPLY_LIGHTING',
  '11_APPLY_DRESSING',
  '12_VALIDATE_CLEARANCES',
  '13_VALIDATE_PROVENANCE',
  '14_BUILD_DEPENDENCY_HASH',
  '15_READY_FOR_BLENDER_ASSEMBLY',
] as const;
export type AssemblyStage = (typeof ASSEMBLY_STAGES)[number];

export const ASSEMBLY_BLOCKERS = [
  'MISSING_CHARACTER_ASSET',
  'MISSING_CHARACTER_RIG',
  'MISSING_ENVIRONMENT_SOURCE',
  'MISSING_STORY_PROP',
  'MISSING_LOCATION_VERSION',
  'MISSING_DERIVATIVE',
  'UNAPPROVED_ASSET',
  'QUARANTINED_ASSET',
  'PROVENANCE_UNKNOWN',
  'HASH_MISMATCH',
  'VERSION_MISMATCH',
  'CAMERA_RIG_MEASUREMENT_UNRESOLVED',
  'VISUAL_APPROVAL_STALE',
  'SHOT_DEPENDENCY_MISMATCH',
] as const;
export type AssemblyBlocker = (typeof ASSEMBLY_BLOCKERS)[number];

export const ASSEMBLY_READINESS = [
  'PLANNING_READY',
  'WAITING_FOR_ASSETS',
  'WAITING_FOR_CHARACTER_RIGS',
  'WAITING_FOR_DERIVATIVES',
  'WAITING_FOR_PROVENANCE',
  'READY_FOR_SYNTHETIC_ASSEMBLY',
  'READY_FOR_REAL_ASSEMBLY',
  'ASSEMBLY_BLOCKED',
  'ASSEMBLED_PENDING_VISUAL_APPROVAL',
  'VISUALLY_APPROVED',
  'READY_FOR_RENDER_PREFLIGHT',
] as const;
export type AssemblyReadiness = (typeof ASSEMBLY_READINESS)[number];

export const ENVIRONMENT_ROLES = [
  'BUILDING_HERO',
  'BUILDING_SUPPORT',
  'TREE_HERO',
  'TREE_SUPPORT',
  'TREE_BACKGROUND',
  'GRASS',
  'FLOWERS',
  'SHRUBS',
  'PATH',
  'ROCK',
  'WATER',
  'SKY',
  'SIGNAGE',
  'STREET_PROP',
  'STORY_PROP',
  'FOREGROUND_FRAME',
  'BACKGROUND_FILL',
] as const;
export type EnvironmentRole = (typeof ENVIRONMENT_ROLES)[number];

export const VEGETATION_ROLES = ['TREE_HERO', 'TREE_SUPPORT', 'TREE_BACKGROUND', 'GRASS', 'FLOWERS', 'SHRUBS'] as const;
