import Link from 'next/link';
import { compileEp001DialogueAnimationManifest } from '@/lib/tivvlejoy-ep001-dialogue-animation-manifest';

export const dynamic = 'force-dynamic';
export const metadata = { title: 'Episode 1 Dialogue Animation Manifest | TivvleJoy', description: 'Exact line-level dialogue, facial and gesture application plan.' };

export default function Ep001DialogueAnimationManifestPage() {
  const manifest = compileEp001DialogueAnimationManifest();
  return <main className="mx-auto min-h-screen w-full max-w-6xl space-y-4 px-4 py-6 sm:px-6 sm:py-10">
    <section className="studio-card p-4 sm:p-6"><Link href="/episode-one/map-prop-handoff" className="inline-flex min-h-touch items-center text-sm font-bold text-[var(--color-primary)]">← Map prop handoff</Link><p className="mt-3 text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-primary)]">Episode 1 dialogue animation</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">All eight lines already have facial and gesture application rules</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-[var(--color-text-muted)]">The logical performance plan is complete while real audio remains intentionally unbound. Exact approved audio/timing receipts are required before final mouth/beak animation can execute.</p><dl className="mt-5 grid gap-px overflow-hidden rounded-xl bg-[var(--color-border)] sm:grid-cols-5">{[['Lines',manifest.metrics.lineCount],['Pip',manifest.metrics.pipLineCount],['Goat',manifest.metrics.goatLineCount],['Animated',manifest.metrics.animatedCount],['Approved',manifest.metrics.approvedCount]].map(([k,v]) => <div key={String(k)} className="bg-[var(--color-surface)] p-3"><dt className="text-xs font-bold uppercase text-[var(--color-text-muted)]">{k}</dt><dd className="mt-1 font-display text-2xl font-bold">{v}</dd></div>)}</dl></section>
    <section className="space-y-3">{manifest.lines.map((line) => <article key={line.lineId} className="studio-card p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-mono text-xs font-bold text-[var(--color-primary)]">{line.lineId} · {line.shotId}</p><h2 className="mt-1 font-display text-xl font-bold">{line.speaker}: “{line.text}”</h2></div><span className="status-warning rounded-full px-3 py-1 text-xs font-bold">real audio unbound</span></div><p className="mt-3 text-sm text-[var(--color-text-muted)]">{line.delivery}</p><div className="mt-4 grid gap-4 sm:grid-cols-3"><div><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Timing</p><p className="mt-1 font-mono text-xs">frames {line.startFrame}–{line.endFrame}</p><p className="mt-1 text-xs">lead {line.minimumActingLeadFrames} · settle {line.minimumActingSettleFrames}</p></div><div><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Face controls</p><p className="mt-1 font-mono text-xs leading-5">{line.faceControls.join(', ')}</p></div><div><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Gesture controls</p><p className="mt-1 font-mono text-xs leading-5">{line.gestureControls.join(', ')}</p></div></div></article>)}</section>
    <section className="rounded-3xl border border-[var(--color-warning)] bg-[var(--color-warning-soft)] p-4 text-sm leading-6 text-[var(--color-warning-foreground)]"><p className="font-bold">No dialogue animation has been executed.</p><p className="mt-1">Real approved voice receipts, line/word timing, canonical adapters, Blender execution and human performance review remain mandatory.</p><p className="mt-3 break-all font-mono text-[11px]">Manifest SHA-256: {manifest.dialogueAnimationManifestSha256}</p></section>
  </main>;
}
