import Link from 'next/link';
import { compileEp001DialoguePerformanceTiming } from '@/lib/tivvlejoy-ep001-dialogue-performance-timing';

export const metadata = {
  title: 'Episode 1 Dialogue Performance | TivvleJoy',
  description: 'Read-only dialogue, facial timing, and performance evidence manifest for EP001.',
};

export default function EpisodeOneDialoguePerformancePage() {
  const timing = compileEp001DialoguePerformanceTiming();
  return (
    <main className="mx-auto min-h-screen w-full max-w-6xl space-y-4 px-4 py-6 sm:px-6 sm:py-10">
      <section className="studio-card overflow-hidden"><div className="border-b border-[var(--color-border)] bg-[var(--color-surface-subtle)] p-4 sm:p-6"><Link href="/episode-one/production-gateway" className="inline-flex min-h-touch items-center text-sm font-bold text-[var(--color-primary)]">← Episode 1 production gateway</Link><div className="mt-3 flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-primary)]">Episode 1 facial performance</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">Dialogue performance timing</h1></div><span className="status-warning rounded-full px-3 py-1 text-xs font-bold">Real audio + rigs unbound</span></div><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--color-text-muted)]">Picture windows are prepared now, but final word, phoneme, viseme, blink, eye, expression, and gesture timing cannot be authored until the exact approved audio and admitted character rig are bound.</p></div><div className="grid gap-px bg-[var(--color-border)] sm:grid-cols-4"><div className="bg-[var(--color-surface)] p-4"><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Dialogue lines</p><p className="mt-1 font-display text-2xl font-bold">{timing.metrics.dialogueLineCount}</p></div><div className="bg-[var(--color-surface)] p-4"><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Pip lines</p><p className="mt-1 font-display text-2xl font-bold">{timing.metrics.pipLineCount}</p></div><div className="bg-[var(--color-surface)] p-4"><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Goat lines</p><p className="mt-1 font-display text-2xl font-bold">{timing.metrics.goatLineCount}</p></div><div className="bg-[var(--color-surface)] p-4"><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Approved bindings</p><p className="mt-1 font-display text-2xl font-bold">0</p></div></div></section>

      <section className="studio-card p-4 sm:p-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-primary)]">Picture-locked dialogue windows</p><div className="mt-4 space-y-3">{timing.lines.map((line) => <article key={line.lineId} className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface-subtle)] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-xs font-bold text-[var(--color-primary)]">{line.lineId} · {line.shotId} · {line.speaker}</p><p className="mt-1 text-sm font-semibold">{line.text}</p><p className="mt-2 text-xs text-[var(--color-text-muted)]">frames {line.pictureWindow.startFrame}–{line.pictureWindow.endFrame} · {line.pictureWindow.durationFrames} frames · pre {line.pictureWindow.preRollFrames} / post {line.pictureWindow.postRollFrames}</p></div><span className="rounded-full border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-1 text-xs font-bold">Awaiting approved audio</span></div></article>)}</div></section>

      <section className="studio-card p-4 sm:p-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-primary)]">Performance gates</p><h2 className="mt-2 font-display text-2xl font-bold">Eight checks before final facial animation</h2><ol className="mt-4 space-y-2">{timing.qualityGates.map((gate) => <li key={gate.gateId} className="rounded-xl bg-[var(--color-surface-subtle)] p-3 text-sm leading-6"><span className="mr-2 font-mono text-xs font-bold text-[var(--color-primary)]">{gate.gateId}</span>{gate.label}</li>)}</ol></section>

      <section className="studio-card p-4 sm:p-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-primary)]">Fail-closed timing rules</p><ul className="mt-4 grid gap-2 sm:grid-cols-2">{timing.timingRules.map((rule) => <li key={rule} className="rounded-xl border border-[var(--color-warning)] bg-[var(--color-warning-soft)] p-3 text-sm leading-5 text-[var(--color-warning-foreground)]">{rule}</li>)}</ul></section>

      <section className="rounded-3xl border border-[var(--color-success)] bg-[var(--color-success-soft)] p-4 text-sm leading-6 text-[var(--color-success-foreground)]"><p className="font-bold">Timing manifest only</p><p className="mt-1">No audio bytes · no rig bytes · no provider calls · Blender not launched · zero keyframes · zero paid requests · no Production mutations</p><p className="mt-3 break-all font-mono text-[11px]">Timing manifest sha256:{timing.timingManifestSha256}</p></section>
    </main>
  );
}
