import Link from 'next/link';
import { compileEp001MapPropHandoff } from '@/lib/tivvlejoy-ep001-map-prop-handoff';

export const dynamic = 'force-dynamic';
export const metadata = { title: 'Episode 1 Map Prop Handoff | TivvleJoy', description: 'Fail-closed state machine for story-map and map-fragment ownership.' };

export default function Ep001MapPropHandoffPage() {
  const plan = compileEp001MapPropHandoff();
  return <main className="mx-auto min-h-screen w-full max-w-6xl space-y-4 px-4 py-6 sm:px-6 sm:py-10">
    <section className="studio-card p-4 sm:p-6"><Link href="/episode-one/per-shot-character-integration" className="inline-flex min-h-touch items-center text-sm font-bold text-[var(--color-primary)]">← Per-shot character integration</Link><p className="mt-3 text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-primary)]">Episode 1 prop continuity</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">Map ownership is a state machine, not a parenting guess</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-[var(--color-text-muted)]">Canonical STORY_MAP and MAP_FRAGMENT cues create explicit world/character transitions. Null-character magic cues cannot invent ownership, and the fragment merge remains human-bound until an exact animation frame is approved.</p><dl className="mt-5 grid gap-px overflow-hidden rounded-xl bg-[var(--color-border)] sm:grid-cols-5">{[['Map cues',plan.metrics.storyMapCueCount],['Map transitions',plan.metrics.storyMapTransitionCount],['Fragment cues',plan.metrics.fragmentCueCount],['Executed',plan.metrics.executedTransitionCount],['Approved',plan.metrics.approvedTransitionCount]].map(([k,v]) => <div key={String(k)} className="bg-[var(--color-surface)] p-3"><dt className="text-xs font-bold uppercase text-[var(--color-text-muted)]">{k}</dt><dd className="mt-1 font-display text-2xl font-bold">{v}</dd></div>)}</dl></section>
    <section className="studio-card p-4 sm:p-6"><h2 className="font-display text-2xl font-bold">Story map transitions</h2><div className="mt-4 space-y-3">{plan.storyMap.transitions.map((item) => <article key={item.transitionId} className="rounded-xl border border-[var(--color-border)] p-3"><div className="flex flex-wrap justify-between gap-2"><p className="font-mono text-xs font-bold">{item.transitionId} · {item.shotId} · frame {item.frame}</p><span className="rounded-full border border-[var(--color-border)] px-3 py-1 text-xs font-bold">{item.fromState} → {item.toState}</span></div><p className="mt-2 text-sm">{item.syncTarget}</p><p className="mt-2 font-mono text-[11px] text-[var(--color-text-muted)]">{item.outgoingAnchor} → {item.incomingAnchor} · preserve world transform: yes</p></article>)}</div></section>
    <section className="studio-card p-4 sm:p-6"><h2 className="font-display text-2xl font-bold">Map fragment transitions</h2><div className="mt-4 space-y-3">{plan.mapFragment.transitions.map((item) => <article key={item.transitionId} className="rounded-xl border border-[var(--color-border)] p-3"><p className="font-mono text-xs font-bold">{item.transitionId} · {item.shotId} · frame {item.frame}</p><p className="mt-2 text-sm">{item.syncTarget}</p><p className="mt-2 font-mono text-[11px]">→ {item.toState} via {item.incomingAnchor}</p></article>)}</div><div className="mt-4 rounded-xl border border-[var(--color-warning)] bg-[var(--color-warning-soft)] p-3 text-sm text-[var(--color-warning-foreground)]"><p className="font-bold">Fragment merge: HUMAN_BINDING_REQUIRED</p><p className="mt-1">A magic sparkle cue alone cannot decide the exact merge frame or attachment behavior.</p></div></section>
    <section className="rounded-3xl border border-[var(--color-warning)] bg-[var(--color-warning-soft)] p-4 text-sm leading-6 text-[var(--color-warning-foreground)]"><p className="font-bold">No constraint switch has been executed.</p><p className="mt-1">Every real handoff will require frame-1 / frame / frame+1 visual continuity review before approval.</p><p className="mt-3 break-all font-mono text-[11px]">State-machine SHA-256: {plan.mapPropHandoffSha256}</p></section>
  </main>;
}
