import Link from 'next/link';
import { compileEp001CharacterSceneIntegration } from '@/lib/tivvlejoy-character-scene-integration';

export const dynamic = 'force-dynamic';
export const metadata = { title: 'Character Scene Integration | TivvleJoy', description: 'Non-destructive scene-integration contract for approved Pip and Goat packages.' };

export default function CharacterSceneIntegrationPage() {
  const plan = compileEp001CharacterSceneIntegration();
  return <main className="mx-auto min-h-screen w-full max-w-7xl space-y-4 px-4 py-6 sm:px-6 sm:py-10">
    <section className="studio-card p-4 sm:p-6"><Link href="/episode-one/character-production-package" className="inline-flex min-h-touch items-center text-sm font-bold text-[var(--color-primary)]">← Character production package</Link><p className="mt-3 text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-primary)]">Episode 1 character integration</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">Approved character packages already know how to enter a shot</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-[var(--color-text-muted)]">The approved source stays read-only. Episode scenes link the character collection, create animation-safe library overrides, target canonical controls, keep shot actions isolated, and invalidate caches whenever the rig or adapter identity changes.</p><p className="mt-4 break-all font-mono text-[11px]">Integration SHA-256: {plan.ep001CharacterSceneIntegrationSha256}</p></section>
    <div className="grid gap-4 xl:grid-cols-2">{[plan.pip, plan.goat].map((item) => <section key={item.characterId} className="studio-card p-4 sm:p-5"><p className="text-xs font-bold uppercase text-[var(--color-primary)]">{item.displayName}</p><h2 className="mt-1 font-display text-2xl font-bold">{item.sceneCollection}</h2><dl className="mt-4 grid gap-px overflow-hidden rounded-xl bg-[var(--color-border)] sm:grid-cols-3">{[['Controls', item.requiredCanonicalControls.length],['Relative scale', item.relativeScale],['Action prefix', item.actionPrefix]].map(([k,v]) => <div key={String(k)} className="bg-[var(--color-surface)] p-3"><dt className="text-xs font-bold uppercase text-[var(--color-text-muted)]">{k}</dt><dd className="mt-1 font-bold">{v}</dd></div>)}</dl><h3 className="mt-5 font-bold">Source policy</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-[var(--color-text-muted)]"><li>read-only approved source .blend</li><li>linked character collection + scene library override</li><li>no destructive append into episode scenes</li><li>animation targets canonical adapter roles</li></ul></section>)}</div>
    <section className="studio-card p-4 sm:p-6"><h2 className="font-display text-2xl font-bold">Pair integration checks</h2><ul className="mt-4 grid gap-2 sm:grid-cols-2">{['Goat:Pip relative scale locked at 1.5×','shared ground-contact review','character interpenetration review','eye-line compatibility review','map/prop handoff continuity','9:16 camera-safe framing'].map((item) => <li key={item} className="rounded-xl border border-[var(--color-border)] p-3 text-sm">{item}</li>)}</ul></section>
    <section className="rounded-3xl border border-[var(--color-warning)] bg-[var(--color-warning-soft)] p-4 text-sm leading-6 text-[var(--color-warning-foreground)]"><p className="font-bold">Scene integration is prepared, not executed.</p><p className="mt-1">No approved character package is bound here yet, no Blender scene was modified, and no animation was written.</p></section>
  </main>;
}
