import Link from 'next/link';
import { compileCharacterAnimationQualityStandard } from '@/lib/tivvlejoy-character-animation-quality-standard';

export const metadata = {
  title: 'Animation Quality Standard | TivvleJoy',
  description: 'Read-only production animation quality standard for TivvleJoy characters and episodes.',
};

export default function AnimationQualityStandardPage() {
  const standard = compileCharacterAnimationQualityStandard();
  return (
    <main className="mx-auto min-h-screen w-full max-w-6xl space-y-4 px-4 py-6 sm:px-6 sm:py-10">
      <section className="studio-card overflow-hidden"><div className="border-b border-[var(--color-border)] bg-[var(--color-surface-subtle)] p-4 sm:p-6"><Link href="/episode-one/production-gateway" className="inline-flex min-h-touch items-center text-sm font-bold text-[var(--color-primary)]">← Episode 1 production gateway</Link><div className="mt-3 flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-primary)]">TivvleJoy character performance</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">Animation quality standard</h1></div><span className="status-warning rounded-full px-3 py-1 text-xs font-bold">Standard locked · execution blocked</span></div><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--color-text-muted)] sm:text-base">Defines what “production-ready animation” means: expressive, readable, grounded, character-specific performance rather than stiff auto-rig motion. Technical completion alone cannot pass this standard.</p></div><div className="grid gap-px bg-[var(--color-border)] sm:grid-cols-4"><div className="bg-[var(--color-surface)] p-4"><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Quality pillars</p><p className="mt-1 font-display text-2xl font-bold">{standard.pillars.length}</p></div><div className="bg-[var(--color-surface)] p-4"><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Review passes</p><p className="mt-1 font-display text-2xl font-bold">{standard.reviewPasses.length}</p></div><div className="bg-[var(--color-surface)] p-4"><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Pip rules</p><p className="mt-1 font-display text-2xl font-bold">{standard.characterRules.PIP.length}</p></div><div className="bg-[var(--color-surface)] p-4"><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Goat rules</p><p className="mt-1 font-display text-2xl font-bold">{standard.characterRules.GOAT.length}</p></div></div></section>

      <section className="studio-card p-4 sm:p-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-primary)]">Twelve quality pillars</p><ol className="mt-4 space-y-3">{standard.pillars.map((pillar) => <li key={pillar.pillarId} className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface-subtle)] p-4"><div className="flex gap-3"><span className="font-display text-xl font-bold text-[var(--color-primary)]">{pillar.order}</span><div><p className="font-mono text-xs font-bold text-[var(--color-primary)]">{pillar.pillarId}</p><p className="mt-1 text-sm leading-6">{pillar.acceptanceStandard}</p><p className="mt-2 text-xs text-[var(--color-text-muted)]">Human review required · no auto-approval</p></div></div></li>)}</ol></section>

      <section className="studio-card p-4 sm:p-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-primary)]">Character-specific standards</p><div className="mt-4 grid gap-4 lg:grid-cols-2"><article className="rounded-3xl bg-[var(--color-surface-subtle)] p-4"><h2 className="font-display text-xl font-bold">Pip / Bird</h2><ul className="mt-3 space-y-2">{standard.characterRules.PIP.map((rule) => <li key={rule} className="text-sm leading-6">• {rule}</li>)}</ul></article><article className="rounded-3xl bg-[var(--color-surface-subtle)] p-4"><h2 className="font-display text-xl font-bold">Goat</h2><ul className="mt-3 space-y-2">{standard.characterRules.GOAT.map((rule) => <li key={rule} className="text-sm leading-6">• {rule}</li>)}</ul></article></div></section>

      <section className="studio-card p-4 sm:p-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-primary)]">Review sequence</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{standard.reviewPasses.map((pass) => <article key={pass.passId} className="rounded-2xl bg-[var(--color-surface-subtle)] p-4"><p className="font-mono text-xs font-bold text-[var(--color-primary)]">{pass.passId}</p><p className="mt-1 text-sm leading-6">{pass.purpose}</p></article>)}</div></section>

      <section className="studio-card p-4 sm:p-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-primary)]">Automatic rejection triggers</p><ul className="mt-4 grid gap-2 sm:grid-cols-2">{standard.rejectionTriggers.map((trigger) => <li key={trigger} className="rounded-xl border border-[var(--color-warning)] bg-[var(--color-warning-soft)] p-3 text-sm leading-5 text-[var(--color-warning-foreground)]">{trigger}</li>)}</ul></section>

      <section className="rounded-3xl border border-[var(--color-success)] bg-[var(--color-success-soft)] p-4 text-sm leading-6 text-[var(--color-success-foreground)]"><p className="font-bold">Quality definition only</p><p className="mt-1">No animation/rig bytes · Blender not launched · zero keyframes · zero paid requests · zero storage/Production mutations · no auto-approval</p><p className="mt-3 break-all font-mono text-[11px]">Quality standard sha256:{standard.qualityStandardSha256}</p></section>
    </main>
  );
}
