import { REAL_TODO_LEDGER_SCHEMA, type RealProductionTodo } from './types';

export function compileRealProductionTodoLedger(): {
  schemaVersion: typeof REAL_TODO_LEDGER_SCHEMA;
  items: RealProductionTodo[];
} {
  const items: RealProductionTodo[] = [
    {
      id: 'TODO_RECEIVE_PRODUCTION_RIGS',
      category: 'RIGS',
      status: 'OPEN',
      blocking: true,
      ownerClass: 'RIGGER',
      costClass: 'ZERO',
      requiresHuman: true,
      requiresExternalInput: true,
      evidenceRequired: 'Hashed Pip and Goat Blender sources on /rig-arrival. Files are not present.',
      nextAction: 'Send the rigger the receive list and wait. Do not invent geometry.',
    },
    {
      id: 'TODO_HUMAN_RIG_APPROVAL',
      category: 'RIGS',
      status: 'OPEN',
      blocking: true,
      ownerClass: 'JUSTIN',
      costClass: 'ZERO',
      requiresHuman: true,
      requiresExternalInput: true,
      evidenceRequired: 'Completed checklist through HUMAN APPROVAL issued. No auto approval.',
      nextAction: 'After files arrive, hash, inspect, review test poses, then approve by hand.',
    },
    {
      id: 'TODO_EP012_SPOKEN_TEXT',
      category: 'VOICE',
      status: 'OPEN',
      blocking: true,
      ownerClass: 'JUSTIN',
      costClass: 'ZERO',
      requiresHuman: true,
      requiresExternalInput: true,
      evidenceRequired: 'Canonical spoken text and hash for all seven EP012 dialogue refs.',
      nextAction: 'Write or confirm the seven lines. Character counts stay unknown until then.',
    },
    {
      id: 'TODO_REAL_VOICE_GENERATION',
      category: 'VOICE',
      status: 'OPEN',
      blocking: true,
      ownerClass: 'VOICE_SYSTEM',
      costClass: 'REQUIRES_HUMAN_CONSENT',
      requiresHuman: true,
      requiresExternalInput: true,
      evidenceRequired: 'Real audio receipts with at least line timing. Fixtures remain synthetic-only.',
      nextAction: 'After spoken text and cost approval, generate real receipts. Do not synthesize now.',
    },
    {
      id: 'TODO_SCENERY_FIRST_READ_CONSENT',
      category: 'SCENERY',
      status: 'OPEN',
      blocking: false,
      ownerClass: 'JUSTIN',
      costClass: 'UNKNOWN',
      requiresHuman: true,
      requiresExternalInput: false,
      evidenceRequired: 'Human consent to GET the selected first-read objects while cost remains unknown.',
      nextAction: 'Keep the queue ready. Do not download until consent is explicit.',
    },
    {
      id: 'TODO_SCENERY_HUMAN_APPROVAL',
      category: 'SCENERY',
      status: 'OPEN',
      blocking: true,
      ownerClass: 'JUSTIN',
      costClass: 'ZERO',
      requiresHuman: true,
      requiresExternalInput: true,
      evidenceRequired: 'Human visual approval of inspected EP012 role candidates. Inspection is not approval.',
      nextAction: 'Review candidates after a consented first read. Do not auto-approve a listing.',
    },
    {
      id: 'TODO_TRUSTED_BLENDER_PIN',
      category: 'BLENDER',
      status: 'OPEN',
      blocking: false,
      ownerClass: 'JUSTIN',
      costClass: 'ZERO',
      requiresHuman: true,
      requiresExternalInput: true,
      evidenceRequired: 'Official SHA-256 for blender-4.2.2-linux-x64.tar.xz pinned in-repo.',
      nextAction: 'Resolve 4.2.2 vs 4.2.3 and pin the official digest before any install.',
    },
    {
      id: 'TODO_SYNTHETIC_BLENDER_ACCEPTANCE',
      category: 'BLENDER',
      status: 'OPEN',
      blocking: false,
      ownerClass: 'CURSOR',
      costClass: 'ZERO',
      requiresHuman: false,
      requiresExternalInput: true,
      evidenceRequired: 'BLENDER_SYNTHETIC_ACCEPTANCE_PASS on a factory-startup scene. No commercial files.',
      nextAction: 'Run the synthetic playbook only after the trusted pin exists.',
    },
    {
      id: 'TODO_COMMERCIAL_BLEND_GATES',
      category: 'BLENDER',
      status: 'OPEN',
      blocking: true,
      ownerClass: 'CURSOR',
      costClass: 'ZERO',
      requiresHuman: false,
      requiresExternalInput: true,
      evidenceRequired: 'Every commercial inspection gate true before any purchased .blend opens.',
      nextAction: 'Keep deep inspection closed. The gate is not ready.',
    },
    {
      id: 'TODO_PAID_RENDER_LATER',
      category: 'RENDER',
      status: 'OPEN',
      blocking: false,
      ownerClass: 'PAID_RENDER',
      costClass: 'PAID',
      requiresHuman: true,
      requiresExternalInput: true,
      evidenceRequired: 'Explicit paid-render consent after rigs, voices, scenery, and Blender are real.',
      nextAction: 'Do not launch GPU or contact RunPod in this marathon.',
    },
  ];
  return { schemaVersion: REAL_TODO_LEDGER_SCHEMA, items };
}
