import type { Ep001DialogueLine, Ep001SceneryIntent, Ep001ShotBlueprint } from './types';

export const EP001_STORY = Object.freeze({
  seriesTitle: 'Pip & Goat and the Lost Doodle Map',
  workingTitle: 'Meadow Map Mystery',
  logline:
    'Pip and Goat chase a loose map fragment from their neighborhood into a meadow, combine their different points of view, and reveal the first path on the Lost Doodle Map.',
  audience: 'AGES_5_TO_10',
  theme: 'Different viewpoints become a strength when friends work together.',
  hook: 'A curled doodle-map fragment flutters loose beneath the bakery sign.',
  complication:
    'The fragment disappears at the meadow edge, where neither friend can solve the search alone.',
  payoff:
    'Goat lowers the branch while Pip reaches the missing corner; joined together, the map draws a new path.',
  button: 'Pip proposes adventure before snacks, and Goat answers with an eager happy bounce.',
  canonStatus: 'DRAFT_NONCANONICAL_AWAITING_HUMAN_STORY_APPROVAL',
} as const);

export const EP001_DIALOGUE_LINES: Ep001DialogueLine[] = [
  {
    lineId: 'EP001_DL_01',
    shotId: 'EP001_SH02',
    speaker: 'PIP',
    text: 'Goat, look! A doodle map—with a piece missing.',
    startFrame: 170,
    endFrame: 300,
    delivery: 'Bright discovery; let the missing-piece thought land clearly.',
    voiceReceiptRef: null,
    audioIncluded: false,
  },
  {
    lineId: 'EP001_DL_02',
    shotId: 'EP001_SH03',
    speaker: 'GOAT',
    text: 'Maybe the wind knows where it went.',
    startFrame: 350,
    endFrame: 450,
    delivery: 'Warm, playful confidence; not sarcastic.',
    voiceReceiptRef: null,
    audioIncluded: false,
  },
  {
    lineId: 'EP001_DL_03',
    shotId: 'EP001_SH04',
    speaker: 'PIP',
    text: "Then let's follow that flutter!",
    startFrame: 500,
    endFrame: 630,
    delivery: 'Explorer energy with a clear point toward screen right.',
    voiceReceiptRef: null,
    audioIncluded: false,
  },
  {
    lineId: 'EP001_DL_04',
    shotId: 'EP001_SH06',
    speaker: 'GOAT',
    text: 'I can look low!',
    startFrame: 865,
    endFrame: 985,
    delivery: 'Helpful and proud, while searching beneath the flowers.',
    voiceReceiptRef: null,
    audioIncluded: false,
  },
  {
    lineId: 'EP001_DL_05',
    shotId: 'EP001_SH07',
    speaker: 'PIP',
    text: 'And I can look high!',
    startFrame: 1_045,
    endFrame: 1_180,
    delivery: 'Delighted realization as her gaze finds the branch.',
    voiceReceiptRef: null,
    audioIncluded: false,
  },
  {
    lineId: 'EP001_DL_06',
    shotId: 'EP001_SH08',
    speaker: 'PIP',
    text: 'Together, we found it!',
    startFrame: 1_265,
    endFrame: 1_390,
    delivery: 'Shared victory; Pip looks to Goat before the final word.',
    voiceReceiptRef: null,
    audioIncluded: false,
  },
  {
    lineId: 'EP001_DL_07',
    shotId: 'EP001_SH09',
    speaker: 'GOAT',
    text: 'It drew a brand-new path!',
    startFrame: 1_465,
    endFrame: 1_575,
    delivery: 'Soft wonder growing into excitement.',
    voiceReceiptRef: null,
    audioIncluded: false,
  },
  {
    lineId: 'EP001_DL_08',
    shotId: 'EP001_SH10',
    speaker: 'PIP',
    text: 'Adventure first. Snack second?',
    startFrame: 1_645,
    endFrame: 1_760,
    delivery: 'Cheeky invitation; leave room for Goat’s silent happy bounce.',
    voiceReceiptRef: null,
    audioIncluded: false,
  },
];

export const EP001_SCENERY_INTENTS: Ep001SceneryIntent[] = [
  {
    locationId: 'bakery',
    worldNode: 'HOME_NEIGHBORHOOD',
    archetypeId: 'BAKERY_EXTERIOR',
    requiredRoles: ['BUILDING_HERO', 'SIGNAGE', 'PATH', 'STREET_PROP', 'SKY'],
    bindingState: 'LOGICAL_ROLES_ONLY_AWAITING_APPROVED_RESOLUTION',
    sourceBytesIncluded: false,
    productionWriteAllowed: false,
  },
  {
    locationId: 'main_street',
    worldNode: 'HOME_NEIGHBORHOOD',
    archetypeId: 'VILLAGE_SIDE_STREET',
    requiredRoles: ['BUILDING_SUPPORT', 'PATH', 'STREET_PROP', 'BACKGROUND_FILL', 'SKY'],
    bindingState: 'LOGICAL_ROLES_ONLY_AWAITING_APPROVED_RESOLUTION',
    sourceBytesIncluded: false,
    productionWriteAllowed: false,
  },
  {
    locationId: 'forest_exit',
    worldNode: 'ENCHANTED_OUTSKIRTS',
    archetypeId: 'SPRING_MEADOW',
    requiredRoles: [
      'TREE_HERO',
      'TREE_SUPPORT',
      'GRASS',
      'FLOWERS',
      'PATH',
      'BACKGROUND_FILL',
      'SKY',
    ],
    bindingState: 'LOGICAL_ROLES_ONLY_AWAITING_APPROVED_RESOLUTION',
    sourceBytesIncluded: false,
    productionWriteAllowed: false,
  },
];

export const EP001_SHOT_BLUEPRINTS: Ep001ShotBlueprint[] = [
  {
    shotId: 'EP001_SH01',
    inFrame: 0,
    outFrame: 150,
    durationFrames: 150,
    beat: 'HOOK',
    storyPurpose:
      'Introduce Pip, Goat, their home base, and the moving map fragment in one readable image.',
    action:
      'Pip steps from the bakery as Goat follows; a curled paper fragment flutters beneath the bakery sign.',
    locationId: 'bakery',
    worldNode: 'HOME_NEIGHBORHOOD',
    archetypeId: 'BAKERY_EXTERIOR',
    shotIntent: 'ESTABLISHING',
    cameraTemplateId: 'TJ_CAM_ESTABLISHING_VERTICAL',
    cameraMotion: 'SLOW_PUSH',
    focalTarget: 'PIP_AND_GOAT',
    lightingPresetId: 'TJ_MORNING_WARM',
    lightingIntent: 'WARM_INVITING',
    charactersVisible: ['PIP', 'GOAT'],
    performance: {
      PIP: {
        emotion: 'curious',
        storyGoal: 'begin the day alert to discovery',
        attentionTarget: 'ENVIRONMENT_FEATURE',
        locomotion: 'walk',
        gesture: 'small wing balance',
        intendedActions: ['WALK_FORWARD', 'LOOK_AT_PROP', 'HEAD_TILT'],
      },
      GOAT: {
        emotion: 'warm',
        storyGoal: 'stay close to Pip',
        attentionTarget: 'PIP',
        locomotion: 'walk',
        gesture: 'gentle head bob',
        intendedActions: ['WALK_FORWARD', 'LOOK_AT_CHARACTER', 'GOAT_HEAD_BOB'],
      },
    },
    dialogueLineIds: [],
    sfx: ['FOOTSTEP_SOFT', 'HOOF_SOFT', 'SCARF_RUSTLE'],
    ambience: 'VILLAGE_DAY',
    musicRole: 'OPENING_HOOK',
    continuity: [
      'Pip wears scarf, backpack, both straps, and copper spiral.',
      'Goat wears collar and round Goat tag.',
      'Travel direction begins screen right.',
    ],
  },
  {
    shotId: 'EP001_SH02',
    inFrame: 150,
    outFrame: 330,
    durationFrames: 180,
    beat: 'DISCOVERY',
    storyPurpose: 'Make the torn map and missing corner unmistakable.',
    action: 'Pip catches the fragment, unfolds it, and shows the torn corner to Goat.',
    locationId: 'bakery',
    worldNode: 'HOME_NEIGHBORHOOD',
    archetypeId: 'BAKERY_EXTERIOR',
    shotIntent: 'PROP_INSERT',
    cameraTemplateId: 'TJ_CAM_STORY_PROP_INSERT',
    cameraMotion: 'STATIC',
    focalTarget: 'STORY_PROP',
    lightingPresetId: 'TJ_MORNING_WARM',
    lightingIntent: 'WARM_INVITING',
    charactersVisible: ['PIP', 'GOAT'],
    performance: {
      PIP: {
        emotion: 'surprised',
        storyGoal: 'show Goat the missing map piece',
        attentionTarget: 'STORY_MAP',
        locomotion: 'stationary',
        gesture: 'careful two-wing hold',
        intendedActions: ['PICK_UP', 'HOLD_PROP', 'LOOK_AT_PROP', 'BEAK_OR_MOUTH_OPEN'],
        propAction: 'PICK_UP',
      },
      GOAT: {
        emotion: 'curious',
        storyGoal: 'inspect without crowding Pip',
        attentionTarget: 'STORY_MAP',
        locomotion: 'approach',
        gesture: 'small head lean',
        intendedActions: ['LOOK_AT_PROP', 'HEAD_TILT', 'STOP'],
      },
    },
    dialogueLineIds: ['EP001_DL_01'],
    sfx: ['MAP_UNFOLD', 'WING_FLUTTER'],
    ambience: 'VILLAGE_DAY',
    musicRole: 'DISCOVERY',
    continuity: [
      'Pip becomes carrier of STORY_MAP.',
      'Missing upper-right corner remains visible.',
      'Goat stays frame right.',
    ],
  },
  {
    shotId: 'EP001_SH03',
    inFrame: 330,
    outFrame: 480,
    durationFrames: 150,
    beat: 'QUESTION',
    storyPurpose: 'Let Goat notice the wind-borne clue and propose the search.',
    action: 'Goat’s ears and gaze track a second flutter crossing behind Pip toward screen right.',
    locationId: 'bakery',
    worldNode: 'HOME_NEIGHBORHOOD',
    archetypeId: 'BAKERY_EXTERIOR',
    shotIntent: 'REACTION',
    cameraTemplateId: 'TJ_CAM_GOAT_MEDIUM',
    cameraMotion: 'PAN',
    focalTarget: 'GOAT',
    lightingPresetId: 'TJ_MORNING_WARM',
    lightingIntent: 'WARM_INVITING',
    charactersVisible: ['PIP', 'GOAT'],
    performance: {
      PIP: {
        emotion: 'curious',
        storyGoal: 'protect the map fragment',
        attentionTarget: 'GOAT',
        locomotion: 'stationary',
        gesture: 'hold map close',
        intendedActions: ['HOLD_PROP', 'LOOK_AT_CHARACTER'],
        propAction: 'HOLD_PROP',
      },
      GOAT: {
        emotion: 'playful',
        storyGoal: 'identify where the clue is going',
        attentionTarget: 'ENVIRONMENT_FEATURE',
        locomotion: 'turn',
        gesture: 'ear-and-head reaction',
        intendedActions: ['LOOK_RIGHT', 'GOAT_EAR_REACTION', 'BEAK_OR_MOUTH_OPEN', 'TURN_RIGHT'],
      },
    },
    dialogueLineIds: ['EP001_DL_02'],
    sfx: ['SCARF_RUSTLE'],
    ambience: 'VILLAGE_DAY',
    musicRole: 'MYSTERY',
    continuity: ['STORY_MAP stays with Pip.', 'Flutter exits screen right.', 'No axis break.'],
  },
  {
    shotId: 'EP001_SH04',
    inFrame: 480,
    outFrame: 660,
    durationFrames: 180,
    beat: 'DECISION',
    storyPurpose: 'Turn curiosity into a shared goal.',
    action: 'Pip points toward the flutter; Goat shifts into a ready stance beside her.',
    locationId: 'main_street',
    worldNode: 'HOME_NEIGHBORHOOD',
    archetypeId: 'VILLAGE_SIDE_STREET',
    shotIntent: 'MEDIUM_TWO_SHOT',
    cameraTemplateId: 'TJ_CAM_TWO_SHOT_MEDIUM',
    cameraMotion: 'SLOW_PULL',
    focalTarget: 'PIP_AND_GOAT',
    lightingPresetId: 'TJ_DAY_ADVENTURE',
    lightingIntent: 'BRIGHT_ADVENTURE',
    charactersVisible: ['PIP', 'GOAT'],
    performance: {
      PIP: {
        emotion: 'determined',
        storyGoal: 'invite Goat into the search',
        attentionTarget: 'DESTINATION',
        locomotion: 'stationary',
        gesture: 'large readable wing point',
        intendedActions: ['POINT', 'BEAK_OR_MOUTH_OPEN', 'HOLD_PROP'],
        propAction: 'HOLD_PROP',
      },
      GOAT: {
        emotion: 'happy',
        storyGoal: 'accept the shared adventure',
        attentionTarget: 'PIP',
        locomotion: 'stationary',
        gesture: 'eager nod',
        intendedActions: ['LOOK_AT_CHARACTER', 'HEAD_NOD', 'HAPPY_BOUNCE'],
      },
    },
    dialogueLineIds: ['EP001_DL_03'],
    sfx: ['WING_FLUTTER', 'COMEDY_BUMP'],
    ambience: 'VILLAGE_DAY',
    musicRole: 'ADVENTURE',
    continuity: [
      'Pip still carries STORY_MAP.',
      'Exit direction remains screen right.',
      'Goat is approximately 1.5 times Pip’s height.',
    ],
  },
  {
    shotId: 'EP001_SH05',
    inFrame: 660,
    outFrame: 840,
    durationFrames: 180,
    beat: 'MOVEMENT',
    storyPurpose: 'Move from the familiar neighborhood to the meadow without losing geography.',
    action:
      'Pip and Goat follow the flutter through the street and arrive at the enchanted meadow edge.',
    locationId: 'forest_exit',
    worldNode: 'ENCHANTED_OUTSKIRTS',
    archetypeId: 'SPRING_MEADOW',
    shotIntent: 'LOCATION_TRANSITION',
    cameraTemplateId: 'TJ_CAM_FOLLOW_ADVENTURE',
    cameraMotion: 'FOLLOW',
    focalTarget: 'PIP_AND_GOAT',
    lightingPresetId: 'TJ_DAY_ADVENTURE',
    lightingIntent: 'BRIGHT_ADVENTURE',
    charactersVisible: ['PIP', 'GOAT'],
    performance: {
      PIP: {
        emotion: 'determined',
        storyGoal: 'keep the flutter in sight',
        attentionTarget: 'DESTINATION',
        locomotion: 'run',
        gesture: 'balanced running wings',
        intendedActions: ['RUN', 'LOOK_AT_PROP', 'HOLD_PROP'],
        propAction: 'HOLD_PROP',
      },
      GOAT: {
        emotion: 'happy',
        storyGoal: 'match Pip’s direction and pace',
        attentionTarget: 'DESTINATION',
        locomotion: 'run',
        gesture: 'playful run',
        intendedActions: ['RUN', 'LOOK_RIGHT', 'GOAT_HEAD_BOB'],
      },
    },
    dialogueLineIds: [],
    sfx: ['FOOTSTEP_SOFT', 'HOOF_SOFT', 'BACKPACK_RUSTLE'],
    ambience: 'FOREST_DAY',
    musicRole: 'ADVENTURE',
    continuity: [
      'Map carrier remains Pip.',
      'Screen-right travel persists across the location cut.',
      'Arrival ends with both feet/hooves planted.',
    ],
  },
  {
    shotId: 'EP001_SH06',
    inFrame: 840,
    outFrame: 1_020,
    durationFrames: 180,
    beat: 'TENSION',
    storyPurpose: 'Show Goat’s useful low viewpoint after the fragment vanishes.',
    action: 'At the meadow edge, Goat searches under flowers while Pip scans the middle distance.',
    locationId: 'forest_exit',
    worldNode: 'ENCHANTED_OUTSKIRTS',
    archetypeId: 'SPRING_MEADOW',
    shotIntent: 'MEDIUM_TWO_SHOT',
    cameraTemplateId: 'TJ_CAM_GOAT_MEDIUM',
    cameraMotion: 'STATIC',
    focalTarget: 'GOAT',
    lightingPresetId: 'TJ_DAY_ADVENTURE',
    lightingIntent: 'BRIGHT_ADVENTURE',
    charactersVisible: ['PIP', 'GOAT'],
    performance: {
      PIP: {
        emotion: 'curious',
        storyGoal: 'scan beyond the flowers',
        attentionTarget: 'ENVIRONMENT_FEATURE',
        locomotion: 'stationary',
        gesture: 'shade eyes with wing',
        intendedActions: ['LOOK_LEFT', 'LOOK_RIGHT', 'HOLD_PROP'],
        propAction: 'HOLD_PROP',
      },
      GOAT: {
        emotion: 'determined',
        storyGoal: 'search where Pip cannot see',
        attentionTarget: 'MAP_FRAGMENT',
        locomotion: 'approach',
        gesture: 'careful nose-led search',
        intendedActions: ['LOOK_DOWN', 'WALK_SLOW', 'BEAK_OR_MOUTH_OPEN'],
      },
    },
    dialogueLineIds: ['EP001_DL_04'],
    sfx: ['HOOF_SOFT', 'SCARF_RUSTLE'],
    ambience: 'FOREST_DAY',
    musicRole: 'CURIOUS',
    continuity: [
      'Pip holds STORY_MAP open.',
      'Goat searches foreground low.',
      'Flowers are dressing, not an unapproved hero asset.',
    ],
  },
  {
    shotId: 'EP001_SH07',
    inFrame: 1_020,
    outFrame: 1_230,
    durationFrames: 210,
    beat: 'DISCOVERY',
    storyPurpose: 'Show Pip’s high viewpoint finding the missing corner.',
    action: 'Pip spots the map corner caught on a flexible branch above Goat and calls it out.',
    locationId: 'forest_exit',
    worldNode: 'ENCHANTED_OUTSKIRTS',
    archetypeId: 'SPRING_MEADOW',
    shotIntent: 'TILT_REVEAL',
    cameraTemplateId: 'TJ_CAM_PIP_MEDIUM',
    cameraMotion: 'TILT',
    focalTarget: 'PIP',
    lightingPresetId: 'TJ_GOLDEN_HOUR',
    lightingIntent: 'GOLDEN_DISCOVERY',
    charactersVisible: ['PIP', 'GOAT'],
    performance: {
      PIP: {
        emotion: 'surprised',
        storyGoal: 'show Goat the high clue',
        attentionTarget: 'MAP_FRAGMENT',
        locomotion: 'stationary',
        gesture: 'look up then point',
        intendedActions: ['LOOK_UP', 'POINT', 'BEAK_OR_MOUTH_OPEN', 'HOLD_PROP'],
        propAction: 'HOLD_PROP',
      },
      GOAT: {
        emotion: 'curious',
        storyGoal: 'follow Pip’s gaze',
        attentionTarget: 'PIP',
        locomotion: 'turn',
        gesture: 'head tilt upward',
        intendedActions: ['LOOK_AT_CHARACTER', 'LOOK_UP', 'HEAD_TILT'],
      },
    },
    dialogueLineIds: ['EP001_DL_05'],
    sfx: ['WING_FLUTTER', 'SCARF_RUSTLE'],
    ambience: 'FOREST_DAY',
    musicRole: 'DISCOVERY',
    continuity: [
      'Fragment is visible above Goat.',
      'Pip keeps the larger map piece secure.',
      'Screen direction remains readable after the tilt.',
    ],
  },
  {
    shotId: 'EP001_SH08',
    inFrame: 1_230,
    outFrame: 1_440,
    durationFrames: 210,
    beat: 'PAYOFF',
    storyPurpose: 'Pay off cooperation through one shared physical action.',
    action:
      'Goat gently lowers the flexible branch; Pip reaches, retrieves the corner, and looks to Goat before celebrating.',
    locationId: 'forest_exit',
    worldNode: 'ENCHANTED_OUTSKIRTS',
    archetypeId: 'SPRING_MEADOW',
    shotIntent: 'WIDE_TWO_SHOT',
    cameraTemplateId: 'TJ_CAM_REACTION_TWO_SHOT',
    cameraMotion: 'SLOW_PUSH',
    focalTarget: 'PIP_AND_GOAT',
    lightingPresetId: 'TJ_GOLDEN_HOUR',
    lightingIntent: 'GOLDEN_DISCOVERY',
    charactersVisible: ['PIP', 'GOAT'],
    performance: {
      PIP: {
        emotion: 'happy',
        storyGoal: 'retrieve the corner and credit Goat',
        attentionTarget: 'MAP_FRAGMENT',
        locomotion: 'approach',
        gesture: 'reach then shared smile',
        intendedActions: ['REACH', 'PICK_UP', 'LOOK_AT_CHARACTER', 'BEAK_OR_MOUTH_OPEN'],
        propAction: 'PICK_UP',
      },
      GOAT: {
        emotion: 'warm',
        storyGoal: 'bring the clue within Pip’s reach',
        attentionTarget: 'MAP_FRAGMENT',
        locomotion: 'stationary',
        gesture: 'careful branch-lowering body lean',
        intendedActions: ['LOOK_AT_PROP', 'HEAD_NOD', 'STOP'],
      },
    },
    dialogueLineIds: ['EP001_DL_06'],
    sfx: ['OBJECT_PICKUP', 'MAGIC_SPARKLE'],
    ambience: 'FOREST_DAY',
    musicRole: 'HEARTWARMING',
    continuity: [
      'Pip now carries STORY_MAP and MAP_FRAGMENT.',
      'No branch contact is executed until approved rigs and contact controls are bound.',
      'Both faces remain caption-safe.',
    ],
  },
  {
    shotId: 'EP001_SH09',
    inFrame: 1_440,
    outFrame: 1_620,
    durationFrames: 180,
    beat: 'REVEAL',
    storyPurpose: 'Reveal the series engine: the repaired doodle map creates a new path.',
    action:
      'Pip aligns the corner with the map; a drawn line completes itself and points deeper into the enchanted outskirts.',
    locationId: 'forest_exit',
    worldNode: 'ENCHANTED_OUTSKIRTS',
    archetypeId: 'SPRING_MEADOW',
    shotIntent: 'PAN_REVEAL',
    cameraTemplateId: 'TJ_CAM_REVEAL',
    cameraMotion: 'REVEAL',
    focalTarget: 'STORY_PROP',
    lightingPresetId: 'TJ_GOLDEN_HOUR',
    lightingIntent: 'REVEAL_ACCENT',
    charactersVisible: ['PIP', 'GOAT'],
    performance: {
      PIP: {
        emotion: 'surprised',
        storyGoal: 'join the pieces without hiding the drawing',
        attentionTarget: 'STORY_MAP',
        locomotion: 'stationary',
        gesture: 'steady map hold',
        intendedActions: ['HOLD_PROP', 'LOOK_AT_PROP', 'SURPRISE_RECOIL'],
        propAction: 'HOLD_PROP',
      },
      GOAT: {
        emotion: 'surprised',
        storyGoal: 'share the map reveal with Pip',
        attentionTarget: 'STORY_MAP',
        locomotion: 'stationary',
        gesture: 'small wonder recoil',
        intendedActions: ['LOOK_AT_PROP', 'SURPRISE_RECOIL', 'BEAK_OR_MOUTH_OPEN'],
      },
    },
    dialogueLineIds: ['EP001_DL_07'],
    sfx: ['MAGIC_SPARKLE', 'MAP_UNFOLD'],
    ambience: 'MAGICAL_NIGHT',
    musicRole: 'WONDER',
    continuity: [
      'Map is visually whole after alignment.',
      'New path points screen right into ENCHANTED_OUTSKIRTS.',
      'Magic remains safe, warm, and non-threatening.',
    ],
  },
  {
    shotId: 'EP001_SH10',
    inFrame: 1_620,
    outFrame: 1_800,
    durationFrames: 180,
    beat: 'BUTTON',
    storyPurpose: 'End on friendship, forward motion, and a light joke.',
    action:
      'Pip folds the map, proposes the next step, and Goat answers with a happy bounce toward the path.',
    locationId: 'forest_exit',
    worldNode: 'ENCHANTED_OUTSKIRTS',
    archetypeId: 'SPRING_MEADOW',
    shotIntent: 'REACTION',
    cameraTemplateId: 'TJ_CAM_REACTION_TWO_SHOT',
    cameraMotion: 'SLOW_PULL',
    focalTarget: 'PIP_AND_GOAT',
    lightingPresetId: 'TJ_GOLDEN_HOUR',
    lightingIntent: 'GOLDEN_DISCOVERY',
    charactersVisible: ['PIP', 'GOAT'],
    performance: {
      PIP: {
        emotion: 'playful',
        storyGoal: 'invite Goat onto the new path',
        attentionTarget: 'GOAT',
        locomotion: 'walk',
        gesture: 'small wing invitation',
        intendedActions: [
          'BEAK_OR_MOUTH_OPEN',
          'PIP_WING_GESTURE_SMALL',
          'WALK_FORWARD',
          'HOLD_PROP',
        ],
        propAction: 'HOLD_PROP',
      },
      GOAT: {
        emotion: 'happy',
        storyGoal: 'accept the adventure enthusiastically',
        attentionTarget: 'DESTINATION',
        locomotion: 'walk',
        gesture: 'happy bounce into a walk',
        intendedActions: ['HAPPY_BOUNCE', 'WALK_EXCITED', 'GOAT_HEAD_BOB'],
      },
    },
    dialogueLineIds: ['EP001_DL_08'],
    sfx: ['MAP_FOLD', 'COMEDY_BUMP', 'FOOTSTEP_DIRT', 'HOOF_SOFT'],
    ambience: 'FOREST_DAY',
    musicRole: 'ENDING_BUTTON',
    continuity: [
      'Pip carries the repaired STORY_MAP into the next episode.',
      'Both exit screen right.',
      'No final canon or production approval is implied.',
    ],
  },
];
