"""Owned building/cabin/cottage audit. No purchases. No Blender required."""
from __future__ import annotations

OWNED_BUILDING_AUDIT = {
    "schema": "TIVVLEJOY_OWNED_BUILDING_AUDIT_V5",
    "newPurchaseRequired": False,
    "purchasePerformed": False,
    "status": "OWNED_BUILDING_ASSET_UPGRADE_REQUIRED",
    "inspected": [
        {
            "id": "Village_Cabin01A",
            "source": "SRC_VILLAGE_BLEND_ZIP",
            "format": "blend",
            "objects": "Building01_LOD0-3 / Roof01_LOD0-3",
            "geometry": "game-kit LOD",
            "roofVertsLod0": "low thousands",
            "maps": "ALB/NRM/SPE present",
            "windowDepth": "atlas-flat",
            "porch": "weak / painted",
            "rating": "MIDGROUND",
            "heroDistance": "REJECT",
        },
        {
            "id": "Village_Cabin02A",
            "source": "SRC_VILLAGE_BLEND_ZIP",
            "format": "blend",
            "rating": "MIDGROUND",
            "heroDistance": "REJECT",
        },
        {
            "id": "Village_Cabin03A",
            "source": "SRC_VILLAGE_BLEND_ZIP",
            "format": "blend",
            "rating": "MIDGROUND",
            "heroDistance": "REJECT",
        },
        {
            "id": "Village_Cabin04A",
            "source": "SRC_VILLAGE_BLEND_ZIP",
            "format": "blend",
            "objects": "Building04_LOD0-3 / Roof04_LOD0-3",
            "roofVertsLod0": 2403,
            "maps": "ALB/NRM/SPE present",
            "windowDepth": "atlas-flat",
            "porch": "weak / painted",
            "rating": "MIDGROUND",
            "heroDistance": "REJECT",
            "note": "Strongest owned exterior. Still game-kit at hero distance.",
        },
        {
            "id": "Village_Cabin05A",
            "source": "SRC_VILLAGE_BLEND_ZIP",
            "format": "blend",
            "rating": "MIDGROUND",
            "heroDistance": "REJECT",
        },
        {
            "id": "Village_Cabin01B-05B",
            "source": "SRC_VILLAGE_BLEND_ZIP",
            "format": "blend",
            "rating": "BACKGROUND",
            "heroDistance": "REJECT",
        },
        {
            "id": "Village_FBX_Cabin01A-05B",
            "source": "SRC_VILLAGE_FBX_ZIP",
            "format": "fbx",
            "rating": "BACKGROUND",
            "heroDistance": "REJECT",
            "note": "Same kit, worse materials than native blend.",
        },
        {
            "id": "Village_Unity_HDRP_URP_BuiltIn",
            "source": "SRC_VILLAGE_PROJECT_ZIP",
            "format": "unity",
            "rating": "REJECT",
            "heroDistance": "REJECT",
        },
        {
            "id": "Stylized_Tavern_Interior",
            "source": "SRC_STYLIZED_TAVERN_INTERIOR",
            "format": "blend 8.56 MiB",
            "rating": "REJECT",
            "heroDistance": "REJECT",
            "note": "Interior only. No exterior cabin/cottage.",
        },
        {
            "id": "Stylized_Tavern_Textures",
            "source": "SRC_STYLIZED_TAVERN_INTERIOR",
            "format": "texture pack",
            "rating": "REJECT",
            "heroDistance": "REJECT",
            "note": "Interior maps, not an exterior building.",
        },
        {
            "id": "EcoKit_Flora_GN",
            "source": "SRC_FOREST_STYLISED_ECOKIT",
            "format": "blend",
            "rating": "REJECT",
            "heroDistance": "REJECT",
            "note": "Vegetation / rocks. No building.",
        },
        {
            "id": "Forest_Nature_Kit",
            "source": "SRC_FOREST_MODEL_PACKAGE",
            "format": "blend",
            "rating": "REJECT",
            "heroDistance": "REJECT",
            "note": "Trees/props. No cabin.",
        },
        {
            "id": "Louis_Mountains",
            "source": "SRC_LOUIS_BG_MOUNTAINS_V1",
            "format": "blend",
            "rating": "REJECT",
            "heroDistance": "REJECT",
            "note": "Distant mountains only.",
        },
        {
            "id": "3DT_Mountain_Pack",
            "source": "SRC_3DT_MOUNTAIN_PACK_BLENDER",
            "format": "blend",
            "rating": "REJECT",
            "heroDistance": "REJECT",
            "note": "Photoreal mountains. Not a building.",
        },
        {
            "id": "Botaniq_Full",
            "source": "SRC_BOTANIQ_FULL_7_2_0",
            "format": "blend library",
            "rating": "REJECT",
            "heroDistance": "REJECT",
            "note": "Vegetation only.",
        },
    ],
    "bestCandidate": "Village Cabin04A LOD0 (Building04_LOD0 + Roof04_LOD0)",
    "bestRating": "MIDGROUND",
    "heroRating": "REJECT",
    "otherCottageHouseShopBarnHut": "NONE_IN_OWNED_CATALOG",
    "v5Use": "recede Cabin04A into supporting midground so tiled roof / flat walls / weak porch are not hero pixels",
}


def audit_summary() -> dict:
    return {
        "ownedBuildingsInspected": len(OWNED_BUILDING_AUDIT["inspected"]),
        "bestCandidate": OWNED_BUILDING_AUDIT["bestCandidate"],
        "heroMidBackgroundRating": OWNED_BUILDING_AUDIT["bestRating"],
        "heroRating": OWNED_BUILDING_AUDIT["heroRating"],
        "newPurchaseRequired": False,
        "purchasePerformed": False,
        "status": OWNED_BUILDING_AUDIT["status"],
    }
