import type { EntityType, JournalEventType } from './types';

export function eventTypeFor(entityType: EntityType): JournalEventType {
  switch (entityType) {
    case 'EPISODE':
      return 'EPISODE_CREATED';
    case 'SCRIPT_VERSION':
      return 'SCRIPT_VERSION_BOUND';
    case 'VOICE_RECEIPT':
      return 'VOICE_RECEIPT_BOUND';
    case 'APPROVED_ASSET_REFERENCE':
    case 'LOCATION_INSTANCE':
      return 'ASSET_RESOLUTION_BOUND';
    case 'CONTINUITY_FACT':
      return 'CONTINUITY_FACT_ADDED';
    case 'SHOT':
      return 'SHOT_DEPENDENCY_CHANGED';
    case 'PRODUCTION_PACKET':
      return 'PRODUCTION_PACKET_COMPILED';
    case 'VISUAL_APPROVAL_REFERENCE':
      return 'VISUAL_APPROVAL_RECORDED';
    case 'PRODUCTION_JOB':
    case 'RECOVERY_CHECKPOINT':
      return 'JOB_CHECKPOINT_WRITTEN';
    case 'QC_RECEIPT':
      return 'QC_RECEIPT_RECORDED';
    case 'DELIVERY_PACKAGE':
      return 'DELIVERY_PACKAGE_COMPILED';
    case 'PRODUCTION_STATE_NODE':
    case 'PRODUCTION_STATE_EDGE':
      return 'STATE_GRAPH_SNAPSHOTTED';
    case 'BATCH_PLAN':
      return 'BATCH_PLAN_WRITTEN';
    case 'RIG_ADMISSION_REPORT':
    case 'RIG_VERSION_IDENTITY':
      return 'RIG_ADMISSION_RECORDED';
    case 'PERFORMANCE_INTENT':
    case 'DIALOGUE_TIMING_PLAN':
    case 'VISEME_PLAN':
    case 'SHOT_ANIMATION_MANIFEST':
    case 'ANIMATION_CACHE_IDENTITY':
    case 'ANIMATION_BATCH_PLAN':
      return 'ANIMATION_PLAN_WRITTEN';
    case 'ANIMATION_QC_RECEIPT':
      return 'ANIMATION_QC_RECORDED';
    case 'SCENERY_SOURCE_RECEIPT':
      return 'SOURCE_MATERIALIZED';
    case 'SCENERY_INSPECTION_RECEIPT':
      return 'STATIC_FORMAT_INSPECTED';
    case 'SCENERY_LOGICAL_ASSET':
      return 'LOGICAL_ASSET_DISCOVERED';
    case 'SCENERY_APPROVAL_RECEIPT':
      return 'ASSET_APPROVED';
    case 'SCENERY_VISUAL_EVIDENCE':
      return 'VISUAL_REVIEW_REQUESTED';
    case 'SCENERY_QUARANTINE':
      return 'ASSET_ARCHIVED';
    case 'SCENERY_PRODUCTION_LIBRARY':
    case 'SCENERY_REVIEW_DECISION':
      return 'REGISTRY_UPDATED';
    case 'DIRECTOR_INTENT':
    case 'STORY_BEAT_PLAN':
      return 'DIRECTOR_INTENT_CREATED';
    case 'CAMERA_PLAN':
      return 'CAMERA_PLAN_CREATED';
    case 'STAGING_PLAN':
      return 'STAGING_PLAN_CREATED';
    case 'EDITORIAL_TIMELINE':
      return 'EDIT_TIMELINE_CREATED';
    case 'SFX_PLAN':
      return 'SFX_PLAN_CREATED';
    case 'MUSIC_CUE_PLAN':
      return 'MUSIC_PLAN_CREATED';
    case 'CAPTION_PLAN':
      return 'CAPTION_PLAN_CREATED';
    case 'DAILIES_REVIEW':
      return 'REVIEW_NOTE_ADDED';
    case 'REVISION_REQUEST':
      return 'REVISION_REQUESTED';
    case 'FINAL_SHOT_SPEC':
    case 'LIGHTING_DIRECTION':
    case 'VFX_DIRECTION':
      return 'SHOT_APPROVAL_RECORDED';
    case 'DIRECTOR_PACKAGE':
      return 'DIRECTOR_PACKAGE_COMPILED';
    default:
      return 'WORKSPACE_SAVED';
  }
}
