import Link from 'next/link';
import { compileCharacterMotionLibraryContract } from '@/lib/tivvlejoy-character-motion-library-contract';

export const metadata = {
  title: 'Character Motion Library | TivvleJoy',
  description: 'Read-only reusable motion-library contract for approved TivvleJoy character rigs.',
};

export default function CharacterMotionLibraryPage() {
  const library = compileCharacterMotionLibraryContract();
  return (
    <main className="mx-auto min-h-screen w-full max-w-6xl space-y-4 px-4 py-6 sm:px-6 sm:py-10">
      <section className="studio-card overflow-hidden"><div className="border-b border-[var(--color-border)] bg-[var(--color-surface-subtle)] p-4 sm:p-6"><Link href="/animation-quality-standard" className="inline-flex min-h-touch items-center text-sm font-bold text-[var(--color-primary)]">← Animation quality standard</Link><div className="mt-3 flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-primary)]">Reusable character performance</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">Character motion library</h1></div><span className="status-warning rounded-full px-3 py-1 text-xs font-bold">Contract ready · actions not authored</span></div><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--color-text-muted)] sm:text-base">Defines the reusable motion assets to build once the final rigs are admitted. Every action remains bound to an exact rig identity and still requires shot-specific acting, contact, gaze, and continuity review.</p></div><div className="grid gap-px bg-[var(--color-border)] sm:grid-cols-4"><div className="bg-[var(--color-surface)] p-4"><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Shared specs</p><p className="mt-1 font-display text-2xl font-bold">{library.metrics.sharedMotionSpecCount}</p></div><div className="bg-[var(--color-surface)] p-4"><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Pip total</p><p className="mt-1 font-display text-2xl font-bold">{library.metrics.pipTotalMotionSpecCount}</p></div><div className="bg-[var(--color-surface)] p-4"><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Goat total</p><p className="mt-1 font-display text-2xl font-bold">{library.metrics.goatTotalMotionSpecCount}</p></div><div className="bg-[var(--color-surface)] p-4"><p className="text-xs font-bold uppercase text-[var(--color-text-muted)]">Approved actions</p><p className="mt-1 font-display text-2xl font-bold">0</p></div></div></section>

      {library.characters.map((character) => <section key={character.characterId} className="studio-card p-4 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-mono text-xs font-bold text-[var(--color-primary)]">{character.characterId}</p><h2 className="mt-1 font-display text-2xl font-bold">{character.displayName}</h2></div><p className="text-sm font-bold text-[var(--color-text-muted)]">{character.motions.length} planned motions</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{character.motions.map((motion) => <article key={motion.motionId} className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface-subtle)] p-4"><p className="font-mono text-xs font-bold text-[var(--color-primary)]">{motion.motionId}</p><p className="mt-1 text-sm leading-6">{motion.purpose}</p><p className="mt-2 text-xs text-[var(--color-text-muted)]">{motion.loopable ? 'Loopable' : 'One-shot'} · {motion.reviewState}</p></article>)}</div></section>)}

      <section className="studio-card p-4 sm:p-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-primary)]">Rig-bound reuse rules</p><ul className="mt-4 grid gap-2 sm:grid-cols-2">{library.bindingRules.map((rule) => <li key={rule} className="rounded-xl border border-[var(--color-warning)] bg-[var(--color-warning-soft)] p-3 text-sm leading-5 text-[var(--color-warning-foreground)]">{rule}</li>)}</ul></section>

      <section className="rounded-3xl border border-[var(--color-success)] bg-[var(--color-success-soft)] p-4 text-sm leading-6 text-[var(--color-success-foreground)]"><p className="font-bold">Library contract only</p><p className="mt-1">No rig/animation bytes · Blender not launched · zero keyframes · zero paid requests · zero storage/Production mutations · no auto-approval</p><p className="mt-3 break-all font-mono text-[11px]">Motion library contract sha256:{library.motionLibraryContractSha256}</p></section>
    </main>
  );
}
